Map<String, String> enUS = {
  'common_continue': 'Continue',
  'onboarding_language_title': 'Welcome to Job',
  'onboarding_language_subtitle':
  'Revolutionizing the way you find work and workers.',
  'auth_signup_login_title': 'Sign up or Log in',
  'auth_create_account': 'Create Account',
  'auth_details_subtitle': 'Enter your details to access your account',
  'auth_phone_tab': 'Phone',
  'auth_email_tab': 'Email',
  'auth_phone_hint': '+1 (555) 000-0000',
  'auth_email_hint': 'Enter Email',
  'auth_error_enter_phone': 'Please enter your phone number',
  'auth_error_valid_phone': 'Enter a valid phone number (10-15 digits)',
  'auth_error_enter_email': 'Please enter your email',
  'auth_error_valid_email': 'Enter a valid email address',
  'auth_error_general': 'Error',
  'auth_error_something_wrong': 'Something went wrong',
  'auth_error_invalid_response': 'Invalid response from server',
  'auth_error_retry': 'Something went wrong. Please try again.',
  'auth_loader_wait': 'Please wait...',
  'auth_button_continue' : 'Continue',
  'auth_button_loading' : 'loading',
  'api_error_invalid_response': 'Invalid server response',
  'api_error_something_wrong': 'Something went wrong',
  'api_error_no_connection': 'No internet connection or server not reachable',
  'chat_error_load_list': 'Failed to load chat list',
  'chat_error_load_messages': 'Failed to load messages',
  'chat_error_send_message': 'Failed to send message',
  'chat_error_no_response': 'No response received from server',
  'chat_error_unexpected_response': 'Unexpected server response',
  'chat_error_request_failed': 'Request failed',
  'chat_ok': 'OK',
  'profile_error_session_not_found': 'User session not found. Please login again.',
  'job_error_not_logged_in': "You're not logged in. Please log in again and retry.",
  'job_success_posted': 'Job Posted successfully!',
  'job_error_failed_post': 'Failed to post job. Please try again.',
  'job_error_something_went_wrong': 'Something went wrong. Please check your connection and try again.',
  'job_cancelled_success': 'Job has been cancelled.',
  'job_cancelled_unable': 'Unable to cancel job.',
  'job_confirmed_success': 'Job confirmed successfully.',
  'job_confirmed_unable': 'Unable to confirm job.',
  'job_select_worker_success': 'Worker selected successfully.',
  'job_select_worker_unable': 'Unable to select worker.',
  'notif_error_not_logged_in': 'User not logged in',
  'notif_error_server': 'Server error',
  'notif_error_something_went_wrong': 'Something went wrong. Please try again.',
  'status_error_title': 'Error',
  'status_error_update_failed': 'Unable to update status. Please try again.',
  'status_loader_going_online': 'Going online...',
  'status_loader_going_offline': 'Going offline...',
  'status_snackbar_failed_title': 'Update Failed',
  'online_status_empty_response': 'Empty response from server.',
  'online_status_success_msg': 'Status updated successfully!',
  'online_status_failed_msg': 'Failed to update status.',
  'online_status_error_connection': 'Something went wrong. Please check your internet connection.',
  'worker_job_applied_success': 'Applied successfully!',
  'worker_job_complete_success': 'Job marked as completed.',
  'worker_job_complete_unable': 'Unable to complete job.',
  'worker_job_confirm_success': 'Confirmed successfully.',
  'worker_job_confirm_unable': 'Unable to confirm.',
  'worker_job_error_something_went_wrong': 'Something went wrong. Please check your connection and try again.',
  'dialog_logout_title': 'Logout',
  'dialog_logout_subtitle': 'Are you sure you want to logout?',
  'dialog_delete_title': 'Delete',
  'dialog_delete_subtitle': 'This action cannot be undone',
  'dialog_default_logout_title': 'Logout',
  'dialog_default_logout_subtitle': 'Are you sure you want to logout?',
  'dialog_default_confirm_text': 'Logout',
  'dialog_default_cancel_text': 'Cancel',
  'error_default_title': 'Error',
  'success_default_title': 'Success',
  'info_default_title': 'Info',
  'image_picker_title': 'Choose Profile Picture',
  'image_picker_camera': 'Camera',
  'image_picker_gallery': 'Gallery',
  'custom_text_field_search_hint': 'Search...',
  'otp_error_complete_code': 'Please enter the complete 6-digit code',
  'otp_verifying': 'Verifying...',
  'otp_default_invalid': 'Invalid OTP',
  'otp_error_invalid_response': 'Invalid response from server',
  'otp_error_account_blocked_title': 'Account Blocked',
  'otp_error_account_blocked_subtitle': 'Your account has been blocked. Please contact support.',
  'otp_resend_success_title': 'Sent',
  'otp_resend_success_msg': 'A new OTP has been sent.',
  'otp_resend_error_msg': 'Could not resend OTP',
  'otp_error_something_went_wrong': 'Something went wrong. Please try again.',
  'otp_error_default': 'Error',
  'otp_screen_title': 'Verify OTP',
  'otp_screen_subtitle': 'Enter the 6-digit code sent to\n@contact',
  'otp_screen_resending': 'Resending...',
  'otp_screen_resend_prompt': "Didn't receive the code? Resend",
  'otp_screen_button_verifying': 'Verifying...',
  'otp_screen_button_verify': 'Verify',
  'job_card_flexible': 'FLEXIBLE',
  'job_card_attributes': 'ATTRIBUTES',
  'job_card_posted_prefix': 'Posted ',
  'job_card_see_detail': 'See More Detail',
  'client_confirm_worker_selecting': 'Selecting worker...',
  'client_confirm_worker_selected_title': 'Worker Selected',
  'client_confirm_worker_action_failed_title': 'Action Failed',
  'client_confirm_worker_cancelling': 'Cancelling job...',
  'client_confirm_worker_cancelled_title': 'Job Cancelled',
  'client_confirm_worker_completing': 'Marking job as completed...',
  'client_confirm_worker_completed_title': 'Job Completed',
  'client_confirm_worker_header_title': 'Worker Profile',
  'client_confirm_worker_skills': 'Skills',
  'client_confirm_worker_job_budget': 'Job Budget',
  'client_confirm_worker_payment_via': 'Payment via @mode',
  'client_confirm_worker_completed_banner': 'This job has been marked as completed.',
  'client_confirm_worker_cancelled_banner': 'This job has been cancelled.',
  'client_confirm_worker_chat_button': 'Chat with Worker',
  'client_confirm_worker_unavailable': 'Unavailable',
  'client_confirm_worker_cancel_job': 'Cancel Job',
  'client_confirm_worker_accept_worker': 'Accept Worker',
  'client_confirm_worker_mark_completed': 'Mark as Completed',
  'client_confirm_worker_active_strike': '@count active strike',
  'client_confirm_worker_active_strikes': '@count active strikes',
  'client_confirm_worker_applied_for': 'Applied For',
  'client_jobs_error_loading': 'Unable to load your jobs. Pull down to retry.',
  'client_jobs_tab_all': 'All',
  'client_home_welcome': 'Welcome',
  'client_home_discover_jobs': 'Discover Jobs',
  'client_home_subtitle': 'All your posted tasks in one place',
  'client_home_no_jobs': 'No jobs available in this category yet.',
  'client_home_your_posted_jobs': 'Your Posted Jobs',
  'client_home_online': 'ONLINE',
  'client_home_offline': 'OFFLINE',
  'client_home_wallet': 'WALLET',
  'client_home_active_jobs': 'ACTIVE JOBS',
  'client_home_retry': 'Retry',
  'model_worker_unknown': 'Unknown Worker',
  'model_worker_rating_new': 'New',
  'model_job_general': 'General',
  'model_job_untitled': 'Untitled Task',
  'model_job_urgency_urgent': 'Urgent',
  'model_job_urgency_critical': 'Critical',
  'model_job_urgency_flexible': 'Flexible',
  'model_job_urgency_normal': 'Normal',
  'model_job_priority': 'PRIORITY',
  'model_job_budget_hourly': 'Hourly Rate',
  'model_job_budget_negotiable': 'Negotiable',
  'model_job_budget_fixed': 'Fixed Price',
  'model_job_budget_hourly_suffix': '/hr',
  'model_job_budget_hourly_label': 'Hourly',
  'model_job_budget_to_be_discussed': 'To be discussed in chat',
  'model_job_budget_one_time': ' (one-time)',
  'model_job_payment_card': 'Card',
  'model_job_payment_cash': 'Cash',
  'model_job_payment_wallet': 'Wallet',
  'model_job_payment_escrow': 'Escrow',
  'model_job_payment_commission': 'Commission Only',
  'model_job_payment_not_specified': 'Not specified',
  'model_job_datetype_custom': 'Custom Date',
  'model_job_datetype_today': 'Today',
  'job_detail_loading_applicants': 'Loading applicants...',
  'job_detail_refreshing': 'Refreshing...',
  'job_detail_not_found': 'Job not found',
  'job_detail_overview': 'Overview',
  'job_detail_category': 'Category',
  'job_detail_subcategory': 'Sub-category',
  'job_detail_city': 'City',
  'job_detail_location': 'Location',
  'job_detail_status': 'Status',
  'job_detail_budget_payment': 'Budget & Payment',
  'job_detail_budget_type': 'Budget Type',
  'job_detail_amount': 'Amount',
  'job_detail_payment_mode': 'Payment Mode',
  'job_detail_schedule': 'Schedule',
  'job_detail_date': 'Date',
  'job_detail_start_time': 'Start Time',
  'job_detail_end_time': 'End Time',
  'job_detail_date_type': 'Date Type',
  'job_detail_description': 'Description',
  'job_detail_no_description': 'No description provided.',
  'job_detail_attributes': 'Attributes',
  'job_detail_interested_worker': 'Interested Worker',
  'job_detail_no_applicants_yet': 'No one has applied yet',
  'job_detail_worker_applied': '@count worker(s) applied for this job',
  'job_detail_assigned_banner': 'A worker has already been assigned to this job.',
  'job_detail_photos': 'Photos',
  'job_detail_photo_count_single': '@count photo',
  'job_detail_photo_count_plural': '@count photos',
  'job_detail_see_detail': 'See Detail',
  'job_detail_online': 'Online',
  'job_detail_offline': 'Offline',
  'job_detail_strike_single': '@count strike',
  'job_detail_strike_plural': '@count strikes',
  'job_detail_no_workers_applied': 'No workers have applied yet',
  'client_my_job_tab_active': 'Active',
  'client_my_job_tab_completed': 'Completed',
  'client_my_job_tab_cancelled': 'Cancelled',
  'client_my_jobs_title': 'My Jobs',
  'client_my_jobs_empty_prefix': 'No ',
  'client_my_jobs_empty_suffix': ' Jobs Found',
  'client_my_jobs_location_fallback': 'Remote Location',
  'client_my_jobs_date_fallback': 'N/A',
  'client_my_jobs_title_fallback': 'No Title',
  'client_my_jobs_desc_fallback': 'No description available.',
  'client_my_jobs_budget_fixed': 'Fixed',
  'edit_profile_title': 'Edit Profile',
  'edit_profile_change_photo': 'Change Photo',
  'edit_profile_hint_name': 'Full Name',
  'edit_profile_hint_email': 'Email Address',
  'edit_profile_email_fallback': 'Not registered with email',
  'edit_profile_hint_phone': 'Phone Number',
  'edit_profile_btn_cancel': 'Cancel',
  'edit_profile_btn_save': 'Save Changes',
  'favourites_title_my': 'My ',
  'favourites_title_highlight': 'Favourites',
  'favourites_saved_jobs_count': '@count saved job(s)',
  'favourites_empty_title': 'No favourites yet',
  'favourites_empty_subtitle': 'Tap the bookmark icon on any job\nto save it here for later.',
  'help_support_tab_faqs': 'FAQs',
  'help_support_tab_submit_ticket': 'Submit Ticket',
  'help_support_tab_live_chat': 'Live Chat',
  'help_support_title': 'Help & Support',
  'help_support_live_badge': '24/7 LIVE',
  'help_support_kb_section_title': 'KNOWLEDGE BASE & FAQS',
  'help_support_no_results': 'No results found',
  'help_support_direct_assistance_title': 'DIRECT ASSISTANCE',
  'help_support_call_label': 'CALL SUPPORT',
  'help_support_email_label': 'EMAIL US',
  'help_support_search_hint': 'Search answers, guides...',
  'help_support_category_label': 'Category',
  'help_support_select_category_hint': 'Select category',
  'help_support_subject_label': 'Subject',
  'help_support_subject_hint': 'Brief summary of the issue...',
  'help_support_message_label': 'Detailed Message',
  'help_support_message_hint': 'Provide all relevant details of your inquiry...',
  'help_support_submit_ticket_button': 'Submit Ticket',
  'help_support_ai_name': 'Uybor Support AI',
  'help_support_online_operator': 'ONLINE OPERATOR',
  'help_support_chat_input_hint': 'Type your question...',
  'faq_question_escrow': 'How does the payment escrow system work?',
  'faq_answer_escrow': 'When you hire a worker, your payment is held securely in escrow and only released to them once the job is marked complete and approved by you.',
  'faq_category_payment': 'Payment',
  'faq_question_fees': 'Are there any service fees for registering?',
  'faq_answer_fees': 'Creating an account and browsing the platform is completely free. A small service fee is only applied when a job is successfully completed.',
  'faq_question_badges': 'How do worker verification badges work?',
  'faq_answer_badges': 'Workers earn verification badges after submitting valid ID documents and passing our background review process, helping you hire with confidence.',
  'faq_category_verification': 'Verification',
  'faq_question_dispute': 'What should I do if a dispute arises?',
  'faq_answer_dispute': 'Open a support ticket from the Submit Ticket tab with details of the disagreement. Our team will review the case and mediate a fair resolution.',
  'faq_category_disputes': 'Disputes',
  'faq_question_data': 'How is my personal data protected?',
  'faq_answer_data': 'All personal data is encrypted in transit and at rest, and is never shared with third parties without your explicit consent.',
  'faq_category_safety': 'Safety',
  'faq_question_cancel': 'Can I cancel a job after the secure deposit is made?',
  'faq_answer_cancel': 'Yes, you can cancel before the worker starts the job. Depending on timing, a partial cancellation fee may apply as outlined in our policy.',
  'faq_cat_all_articles': 'All Articles',
  'ticket_cat_payment_escrow': 'Payment & Escrow',
  'ticket_cat_verification': 'Verification',
  'ticket_cat_disputes': 'Disputes',
  'ticket_cat_account': 'Account',
  'ticket_cat_technical': 'Technical Issue',
  'ticket_cat_other': 'Other',
  'support_chat_welcome': 'Hello! Welcome to Support. How can we help you today?',
  'support_chat_time_just_now': 'Just now',
  'support_chat_time_now': 'Now',
  'support_chat_auto_reply': 'Thanks for reaching out, one of our agents will respond shortly.',
  'support_snackbar_missing_title': 'Missing details',
  'support_snackbar_missing_msg': 'Please fill in subject and message.',
  'support_snackbar_success_title': 'Ticket submitted',
  'support_snackbar_success_msg': 'Our support team will get back to you soon.',
  'profile_fetch_error_title': 'Error',
  'profile_update_missing_name': 'Name cannot be empty.',
  'profile_update_missing_name_title': 'Oops!',
  'profile_update_loader': 'Saving...',
  'profile_update_failed_title': 'Update Failed',
  'profile_update_fallback_error': 'Something went wrong, please try again.',
  'profile_update_success_title': 'Success',
  'profile_update_success_msg': 'Profile updated successfully!',
  'profile_skill_empty_title': 'Oops!',
  'profile_skill_empty_msg': 'Skill name cannot be empty.',
  'profile_skill_exists_title': 'Already Added',
  'profile_skill_exists_msg': 'This skill is already in your list.',
  'profile_fallback_name': 'Add your name',
  'profile_fallback_email': 'Not provided',
  'profile_fallback_phone': 'Not provided',
  'profile_role_client': 'Client',
  'profile_role_worker': 'Worker',
  'profile_role_prefix': "I'm a @role",
  'client_profile_title': 'Profile',
  'client_profile_online': 'ONLINE',
  'client_profile_offline': 'OFFLINE',
  'client_profile_personal_info': 'Personal Info',
  'client_profile_wallet': 'Wallet',
  'client_profile_favourites': 'Favourites',
  'client_profile_location': 'Location',
  'client_profile_location_subtitle': 'Active for nearby jobs',
  'client_profile_settings': 'Settings',
  'client_profile_help_support': 'Help & Support',
  'client_profile_logout': 'Logout',
  'client_profile_logout_confirm': 'Are you sure you want to logout?',
  'settings_title': 'Settings',
  'settings_lang_title': 'Choose your language',
  'settings_notifications_title': 'Notifications',
  'settings_dark_mode_title': 'Dark Mode',
  'settings_dark_mode_subtitle': 'Switch between light and dark',
  'settings_become_worker_title': 'Become a Worker',
  'settings_switch_btn': 'Switch',
  'settings_info_version_key': 'App Version',
  'settings_info_version_val': '1.2.0 (Stable)',
  'settings_info_status_key': 'Account Status',
  'settings_info_status_val': 'Verified',
  'settings_info_security_key': 'Security',
  'settings_info_security_val': 'SSL/SMS Protected',
  'settings_logout_loader': 'Logging out...',
  'settings_logout_error_title': 'Error',
  'settings_logout_error_msg': 'Could not logout. Please try again.',
  'settings_ctrl_err_session_title': 'Error',
  'settings_ctrl_err_session_msg': 'User session not found.',
  'settings_ctrl_loader_switching': 'Switching Mode...',
  'settings_ctrl_success_title': 'Success',
  'settings_ctrl_success_msg': 'Mode switched successfully',
  'settings_ctrl_err_switch': 'Failed to switch role',
  'settings_ctrl_err_general': 'Something went wrong. Please try again.',
  'settings_ctrl_loader_logout': 'Logging out...',
  'settings_ctrl_err_logout': 'Could not logout. Please try again.',
  'wallet_title': 'Wallet',
  'wallet_balance_title': 'Total Balance',
  'wallet_recent_tx': 'Recent Transactions',
  'wallet_see_all': 'See All',
  'wallet_btn_deposit': '+ Deposit',
  'wallet_btn_withdraw': '- Withdraw',
  'wallet_tx_plumbing': 'Payment for Plumbing',
  'wallet_tx_withdrawal': 'Withdrawal to Bank',
  'wallet_tx_hvac': 'Payment for HVAC',
  'wallet_tx_time_today': 'Today, 2:30 PM',
  'wallet_tx_time_yesterday': 'Yesterday, 4:15 PM',
  'wallet_tx_time_old': 'Mar 5, 11:20 AM',
  'wallet_ctrl_success_title': 'Success',
  'wallet_ctrl_deposit_msg': 'Deposit of \$%s successful',
  'wallet_ctrl_err_balance_title': 'Insufficient Balance',
  'wallet_ctrl_err_balance_msg': 'You don\'t have enough funds to withdraw',
  'wallet_ctrl_withdraw_msg': 'Withdrawal completed successfully',
  'deposit_title': 'Deposit Funds',
  'deposit_select_card': 'SELECT CARD TYPE',
  'deposit_label_amount': 'AMOUNT (\$)',
  'deposit_hint_amount': '\$ 50.00',
  'deposit_label_card_num': 'CARD NUMBER',
  'deposit_hint_card_num': '8600 **** **** ****',
  'deposit_top_uzcard': 'UZCARD (8600)',
  'deposit_label_expiry': 'EXPIRY DATE',
  'deposit_hint_expiry': 'MM/YY',
  'deposit_label_cvv': 'CVV',
  'deposit_hint_cvv': '***',
  'deposit_label_name': 'CARDHOLDER NAME',
  'deposit_hint_name': 'JOHN DOE',
  'deposit_btn_confirm': 'Confirm Deposit',
  'withdraw_title': 'Withdraw Funds',
  'withdraw_amount_label': 'AMOUNT (\$)',
  'withdraw_available_prefix': 'AVAILABLE: \$',
  'withdraw_hint_amount': '\$ 100.00',
  'withdraw_bank_label': 'BANK ACCOUNT (IBAN)',
  'withdraw_hint_iban': 'UZ99 4321 0000 1234 5678',
  'withdraw_btn_confirm': 'Confirm Withdrawal',
  'post_job_title_post_a': 'Post a ',
  'post_job_title_task': 'Task',
  'post_job_subtitle': 'Find the right talent for your gig',
  'post_job_task_title_label': 'Task Title',
  'post_job_task_title_hint': 'e.g. Help moving a sofa',
  'post_job_category_label': 'Category',
  'post_job_select_category_default': 'Select\nCategory',
  'post_job_subcategory_label': 'Sub-Category',
  'post_job_select_subcategory_default': 'Select Sub-\ncategory',
  'post_job_select_category_sheet_title': 'Select Category',
  'post_job_select_subcategory_sheet_title': 'Select Sub-category',
  'post_job_all_subcategories': 'All sub-categories',
  'post_job_location_label': 'Location & Address',
  'post_job_location_hint': 'e.g. 45 Park Avenue, Tashkent',
  'post_job_description_label': 'Description',
  'post_job_description_hint': 'Describe the job requirements and scope...',
  'post_job_budget_title': 'Budget',
  'post_job_budget_subtitle_fixed': 'One-time total payment',
  'post_job_budget_subtitle_hourly': 'Pay for actual hours worked',
  'post_job_budget_subtitle_negotiable': 'Price to be discussed and agreed directly with the worker',
  'post_job_tab_fixed_price': 'Fixed\nPrice',
  'post_job_tab_hourly_rate': 'Hourly\nRate',
  'post_job_tab_negotiable': 'Negotiable',
  'post_job_amount_label': 'Amount',
  'post_job_currency_uzs': 'UZS',
  'post_job_amount_hint': '100',
  'post_job_payment_type_label': 'Payment Type',
  'post_job_rate_per_hour_label': 'Rate per hour',
  'post_job_rate_hint': '25',
  'post_job_estimated_hours_label': 'Estimated Hours',
  'post_job_optional': '(Optional)',
  'post_job_hours_hint': '4',
  'post_job_negotiable_budget_title': 'Negotiable Budget',
  'post_job_negotiable_budget_desc': 'Budget will be discussed and agreed upon with the worker in chat.',
  'post_job_payment_cash': 'Cash',
  'post_job_payment_card': 'Card',
  'post_job_payment_wallet': 'Wallet',
  'post_job_schedule_badge': 'Schedule',
  'post_job_select_start_time_title': 'Select Start Time',
  'post_job_select_start_time_message': 'Please select start time first',
  'post_job_start_time_label': 'Start Time',
  'post_job_end_time_label': 'End Time',
  'post_job_choose_date_label': 'Choose Date',
  'post_job_today': 'Today',
  'post_job_custom_date': 'Custom Date...',
  'post_job_urgency_label': 'Urgency',
  'post_job_urgent': 'Urgent',
  'post_job_flexible': 'Flexible',
  'post_job_photo_attachment_label': 'Photo Attachment',
  'post_job_drag_drop_photos': 'Drag & drop photos or click to browse',
  'post_job_photos_limit_hint': 'Up to 3 photos, JPG or PNG',
  'post_job_cancel_button': 'Cancel',
  'post_job_submit_button': 'Submit',
  'personal_info_title': 'Personal Info',
  'personal_info_label_name': 'FULL NAME',
  'personal_info_label_email': 'EMAIL ADDRESS',
  'personal_info_label_phone': 'PHONE NUMBER',
  'personal_info_btn_edit': 'Edit Profile',
  // Delivery & Logistics
  'category_delivery': 'Delivery & Logistics',
  'category_sub_small_item': 'Small Item & Package Delivery',
  'category_sub_grocery': 'Grocery & Food Delivery',
  'category_sub_heavy_freight': 'Heavy Freight & Cargo',
  'category_sub_document': 'Document & Legal Courier',

  // Handyman & Repairs
  'category_handyman': 'Handyman & Repairs',
  'category_sub_plumbing': 'Plumbing Repair',
  'category_sub_electrical': 'Electrical Repair',
  'category_sub_furniture': 'Furniture Assembly',
  'category_sub_carpentry': 'Carpentry & Woodwork',
  'category_sub_painting': 'Painting & Drywall',
  'category_sub_appliance': 'Appliance Installation & Repair',

  // Cleaning Services
  'category_cleaning': 'Cleaning Services',
  'category_sub_house_clean': 'House & Apartment Cleaning',
  'category_sub_deep_clean': 'Deep & Move-Out Cleaning',
  'category_sub_laundry': 'Laundry & Ironing',
  'category_sub_window_clean': 'Window & Glass Cleaning',
  'category_sub_carpet_clean': 'Carpet & Upholstery Cleaning',

  // Moving & Storage
  'category_moving': 'Moving & Storage',
  'category_sub_local_move': 'Local Moving & Relocation',
  'category_sub_packing': 'Packing & Unpacking Help',
  'category_sub_heavy_lifting': 'Heavy Lifting & Loading',
  'category_sub_office_move': 'Office & Commercial Moving',

  // Pet Care
  'category_pet_care': 'Pet Care',
  'category_sub_pet_sitting': 'Pet Sitting & Boarding',
  'category_sub_dog_walking': 'Dog Walking',
  'category_sub_pet_grooming': 'Pet Grooming & Bathing',
  'category_sub_pet_training': 'Pet Training & Behavior',

  // Tech & IT Support
  'category_tech_it': 'Tech & IT Support',
  'category_sub_computer_repair': 'Computer & Laptop Repair',
  'category_sub_smart_home': 'Smart Home & Wi-Fi Setup',
  'category_sub_phone_repair': 'Mobile & Tablet Repair',
  'category_sub_tv_mounting': 'TV Mounting & Audio Setup',

  // Beauty & Wellness
  'category_beauty_wellness': 'Beauty & Wellness',
  'category_sub_haircut_styling': 'Haircut & Styling',
  'category_sub_makeup': 'Makeup & Beauty Services',
  'category_sub_massage': 'Massage & Spa Therapy',
  'category_sub_nail_care': 'Manicure & Pedicure',

  // Events & Photography
  'category_events_photo': 'Events & Photography',
  'category_sub_event_photography': 'Event & Portrait Photography',
  'category_sub_catering': 'Catering & Baking Services',
  'category_sub_event_planning': 'Party & Event Planning',
  'category_sub_dj_music': 'DJ & Live Music Performance',

  // Automotive Services
  'category_automotive': 'Automotive Services',
  'category_sub_mobile_mechanic': 'Mobile Mechanic & Diagnostics',
  'category_sub_car_wash': 'Mobile Car Wash & Detailing',
  'category_sub_jump_start': 'Battery Jump Start & Towing',

  // Gardening & Outdoor
  'category_gardening': 'Gardening & Outdoor',
  'category_sub_lawn_mowing': 'Lawn Mowing & Yard Care',
  'category_sub_landscaping': 'Landscaping & Plant Design',
  'category_sub_snow_removal': 'Snow Removal & De-icing',
  'category_sub_pool_maintenance': 'Pool Maintenance & Cleaning',

  // Lessons & Tutoring
  'category_lessons_tutoring': 'Lessons & Tutoring',
  'category_sub_academic_tutoring': 'Academic & Math Tutoring',
  'category_sub_language_lessons': 'Language Lessons',
  'category_sub_music_lessons': 'Music & Instrument Lessons',
  'category_sub_fitness_training': 'Personal Fitness Training',

  // Business & Admin
  'category_business_admin': 'Business & Admin Support',
  'category_sub_virtual_assistant': 'Virtual Assistant Services',
  'category_sub_data_entry': 'Data Entry & Typing',
  'category_sub_translation': 'Document Translation',
  'category_sub_graphic_design': 'Graphic Design & Branding',
  // post job controller
  'post_job_time_placeholder': '--:--',
  'post_job_photo_limit_title': 'Limit Reached',
  'post_job_photo_limit_message': 'You can only attach up to 3 photos',
  'post_job_validation_missing_title_title': 'Missing Title',
  'post_job_validation_missing_title_message': 'Please enter a task title',
  'post_job_validation_missing_category_title': 'Missing Category',
  'post_job_validation_missing_category_message': 'Please select a category',
  'post_job_validation_missing_subcategory_title': 'Missing Sub-category',
  'post_job_validation_missing_subcategory_message': 'Please select a sub-category',
  'post_job_validation_missing_location_title': 'Missing Location',
  'post_job_validation_missing_location_message': 'Please enter a location',
  'post_job_validation_missing_description_title': 'Missing Description',
  'post_job_validation_missing_description_message': 'Please describe the task',
  'post_job_validation_missing_amount_title': 'Missing Amount',
  'post_job_validation_missing_amount_message': 'Please enter a budget amount',
  'post_job_validation_missing_rate_title': 'Missing Rate',
  'post_job_validation_missing_rate_message': 'Please enter an hourly rate',
  'post_job_validation_missing_start_time_title': 'Missing Start Time',
  'post_job_validation_missing_start_time_message': 'Please select a start time',
  'post_job_validation_missing_end_time_title': 'Missing End Time',
  'post_job_validation_missing_end_time_message': 'Please select an end time',
  'post_job_success_title': 'Success',
  'post_job_failed_title': 'Failed',
  'nav_home': 'Home',
  'nav_chat': 'Chat',
  'nav_my_jobs': 'My Jobs',
  'nav_profile': 'Profile',
  'post_job_summary_header_review': 'Review & ',
  'post_job_summary_header_confirm': 'Confirm',
  'post_job_summary_header_subtitle': 'Please check everything before posting',
  'post_job_summary_task_details_title': 'Task Details',
  'post_job_summary_title_label': 'Title',
  'post_job_summary_subcategory_label': 'Sub-category',
  'post_job_summary_location_label': 'Location',
  'post_job_summary_budget_payment_title': 'Budget & Payment',
  'post_job_summary_budget_type_label': 'Budget Type',
  'post_job_summary_date_label': 'Date',
  'post_job_summary_budget_fixed_price': 'Fixed Price',
  'post_job_summary_budget_hourly_rate': 'Hourly Rate',
  'post_job_summary_budget_negotiable': 'Negotiable',
  'post_job_summary_amount_one_time': '(one-time)',
  'post_job_summary_amount_per_hour': '/ hour',
  'post_job_summary_amount_hrs_suffix': 'hrs',
  'post_job_summary_amount_negotiable_desc': 'To be discussed in chat',
  'post_job_summary_edit_details_button': 'Edit Details',
  'post_job_summary_confirm_submit_button': 'Confirm & Submit',
  'role_ctrl_err_title': 'Selection Error',
  'role_ctrl_err_msg': 'Please select a role to continue.',
  'tab_all': 'All',
  'tab_pending': 'Pending',
  'tab_ongoing': 'Ongoing',
  'tab_completed': 'Completed',
  'tab_cancelled': 'Cancelled',
  'chat_list_title': 'Messages',
  'chat_list_search_hint': 'Search chats...',
  'chat_list_no_conversations': 'No conversations yet',
  'chat_tile_no_message': 'No message yet',
  'chat_controller_error_title': 'Error',
  'chat_controller_session_expired': 'Login session not found, please log in again.',
  'message_screen_error_title': 'Error',
  'message_screen_send_failed_title': 'Message Failed',
  'message_screen_empty_state': 'No messages yet. Send the first message to start the conversation.',
  'message_screen_voice_message': 'Voice message',
  'message_screen_input_hint': 'Type a message...',
  'notification_time_just_now': 'JUST NOW',
  'notification_time_min_ago': 'M AGO',
  'notification_time_hour_ago': 'H AGO',
  'notification_time_day_ago': 'D AGO',
  'notification_time_month_ago': 'MO AGO',
  'notification_time_year_ago': 'Y AGO',
  'notification_screen_title': 'Notifications',
  "notification_screen_mark_all_read":"Read all",
  'notification_screen_tab_inbox': 'Inbox',
  'notification_screen_tab_settings': 'Settings',
  'notification_screen_load_error_fallback': 'Failed to load notifications',
  'notification_screen_error_title': "Couldn't load notifications",
  'notification_screen_empty_title': 'No notifications yet',
  'notification_screen_empty_subtitle': "We'll let you know when something new comes in.",
  'notification_screen_retry_button': 'Retry',
  'notification_screen_push_title': 'Push Notifications',
  'notification_screen_push_subtitle': 'Instant alerts',
  'notification_screen_email_title': 'Email Notifications',
  'notification_screen_email_subtitle': 'Email messages',
  'notification_screen_sms_title': 'SMS Notifications',
  'notification_screen_sms_subtitle': 'SMS updates',
  'notification_screen_sound_title': 'Sound Notifications',
  'notification_screen_sound_subtitle': 'App sound effects',
  'worker_active_jobs_title': 'Active Jobs',
  'worker_active_jobs_empty': 'No active jobs right now.',
  'worker_job_negotiable': 'Negotiable',
  'worker_job_not_specified': 'Not specified',
  'worker_job_payment_cash': 'Cash',
  'worker_job_payment_card': 'Card',
  'worker_job_payment_escrow': 'Escrow',
  'worker_job_payment_commission': 'Commission Only',
  'worker_job_client_fallback': 'Client',
  'worker_home_no_jobs_in_category': 'No jobs available in @category right now.',
  'worker_home_city_required_title': 'City Required',
  'worker_home_city_required_message': 'Please enter your city to see available jobs.',
  'worker_home_add_city_title': 'Add Your City',
  'worker_home_add_city_subtitle': 'Tell us your city so we can show you jobs posted near you.',
  'worker_home_city_hint': 'e.g. Multan, Lahore, Karachi',
  'worker_home_find_jobs_button': 'Find Jobs',
  'worker_home_jobs_in_city': 'Jobs in @city',
  'worker_home_swipe_subtitle': 'Swipe through the best opportunities',
  'worker_home_no_jobs_in_city': 'No jobs available in @city right now.',
  'worker_home_welcome': 'Welcome',
  'worker_home_online': 'ONLINE',
  'worker_home_offline': 'OFFLINE',
  'worker_home_earnings_label': 'EARNINGS',
  'worker_home_active_label': 'ACTIVE',
  'worker_job_card_selected': 'Worker Selected',
  'worker_job_card_see_detail': 'See Detail',
  'worker_job_history_tab_all': 'All',
  'worker_job_history_tab_active': 'Active',
  'worker_job_history_tab_past': 'Past','worker_job_detail_submitting_application': 'Submitting application...',
  'worker_job_detail_success_title': 'Success',
  'worker_job_detail_application_update_title': 'Application Update',
  'worker_job_detail_not_found': 'Job not found',
  'worker_job_detail_cancelling_job': 'Cancelling job...',
  'worker_job_detail_job_cancelled_title': 'Job Cancelled',
  'worker_job_detail_action_failed_title': 'Action Failed',
  'worker_job_detail_marking_completed': 'Marking job as completed...',
  'worker_job_detail_job_completed_title': 'Job Completed',
  'worker_job_detail_overview_title': 'Overview',
  'worker_job_detail_label_category': 'Category',
  'worker_job_detail_label_city': 'City',
  'worker_job_detail_label_location': 'Location',
  'worker_job_detail_label_status': 'Status',
  'worker_job_detail_budget_title': 'Budget & Payment',
  'worker_job_detail_label_amount': 'Amount',
  'worker_job_detail_label_payment_mode': 'Payment Mode',
  'worker_job_detail_schedule_title': 'Schedule',
  'worker_job_detail_label_date_time': 'Date & Time',
  'worker_job_detail_description_title': 'Description',
  'worker_job_detail_no_description': 'No description provided.',
  'worker_job_detail_posted_by_title': 'Posted By',
  'worker_job_detail_completed_banner': 'You have marked this job as completed.',
  'worker_job_detail_cancelled_banner': 'This job has been cancelled.',
  'worker_job_detail_chat_with_client': 'Chat with Client',
  'worker_job_detail_cancel_job_button': 'Cancel Job',
  'worker_job_detail_mark_completed_button': 'Mark as Completed',
  'worker_job_detail_taken_by_other_banner': 'This job has already been assigned to another worker.',
  'worker_job_detail_waiting_confirmation': "You've applied. Waiting for client confirmation.",
  'worker_job_detail_apply_button': 'Apply',
  'worker_job_detail_online_pill': 'Online',
  'worker_job_detail_offline_pill': 'Offline',
  'worker_job_detail_photos_title': 'Photos',
  'worker_job_detail_photo_count_singular': '@count photo',
  'worker_job_detail_photo_count_plural': '@count photos',
  'job_history_card_payout_label': 'PAYOUT:',
  'worker_history_no_title': 'No Title',
  'worker_history_location_not_specified': 'Location not specified',
  'worker_history_na': 'N/A',
  'worker_history_status_posted': 'POSTED',
  'worker_history_status_applied': 'APPLIED',
  'worker_my_jobs_title': 'My Jobs',
  'worker_my_jobs_empty': 'No jobs found',
  'worker_edit_profile_title': 'Edit Profile',
  'worker_edit_profile_take_photo': 'Take a Photo',
  'worker_edit_profile_choose_gallery': 'Choose from Gallery',
  'worker_edit_profile_no_email': 'Not registered with email',
  'worker_edit_profile_change_photo': 'Change Photo',
  'worker_edit_profile_hint_full_name': 'Full Name',
  'worker_edit_profile_hint_email': 'Email Address',
  'worker_edit_profile_hint_phone': 'Phone Number',
  'worker_edit_profile_skills_label': 'SKILLS',
  'worker_edit_profile_hint_add_skill': 'Add Skill',
  'worker_edit_profile_cancel_button': 'Cancel',
  'worker_edit_profile_saving_button': 'Saving...',
  'worker_edit_profile_save_button': 'Save Changes',
  'worker_favourites_title': 'Favourites',
  'worker_favourites_empty_title': 'No favourite jobs yet.',
  'worker_favourites_empty_subtitle': 'Tap the heart icon on a job to save it here.',
  'worker_help_tab_faqs': 'FAQs',
  'worker_help_tab_submit_ticket': 'Submit Ticket',
  'worker_help_tab_live_chat': 'Live Chat',
  'worker_help_appbar_title': 'Help & Support',
  'worker_help_live_badge': '24/7 LIVE',
  'worker_help_kb_section_title': 'KNOWLEDGE BASE & FAQS',
  'worker_help_no_results': 'No results found',
  'worker_help_direct_assistance_title': 'DIRECT ASSISTANCE',
  'worker_help_call_support_label': 'CALL SUPPORT',
  'worker_help_email_us_label': 'EMAIL US',
  'worker_help_search_hint': 'Search answers, guides...',
  'worker_help_label_category': 'Category',
  'worker_help_label_subject': 'Subject',
  'worker_help_label_detailed_message': 'Detailed Message',
  'worker_help_select_category_hint': 'Select category',
  'worker_help_subject_hint': 'Brief summary of the issue...',
  'worker_help_message_hint': 'Provide all relevant details of your inquiry...',
  'worker_help_submit_ticket_button': 'Submit Ticket',
  'worker_help_support_ai_name': 'Uybor Support AI',
  'worker_help_online_operator': 'ONLINE OPERATOR',
  'worker_help_chat_input_hint': 'Type your question...',
  'faq_escrow_question': 'How does the payment escrow system work?',
  'faq_escrow_answer': 'When you hire a worker, your payment is held securely in escrow and only released to them once the job is marked complete and approved by you.',
  'faq_category_payment': 'Payment',
  'faq_fees_question': 'Are there any service fees for registering?',
  'faq_fees_answer': 'Creating an account and browsing the platform is completely free. A small service fee is only applied when a job is successfully completed.',
  'faq_verification_question': 'How do worker verification badges work?',
  'faq_verification_answer': 'Workers earn verification badges after submitting valid ID documents and passing our background review process, helping you hire with confidence.',
  'faq_category_verification': 'Verification',
  'faq_dispute_question': 'What should I do if a dispute arises?',
  'faq_dispute_answer': 'Open a support ticket from the Submit Ticket tab with details of the disagreement. Our team will review the case and mediate a fair resolution.',
  'faq_category_disputes': 'Disputes',
  'faq_safety_question': 'How is my personal data protected?',
  'faq_safety_answer': 'All personal data is encrypted in transit and at rest, and is never shared with third parties without your explicit consent.',
  'faq_category_safety': 'Safety',
  'faq_cancel_question': 'Can I cancel a job after the secure deposit is made?',
  'faq_cancel_answer': 'Yes, you can cancel before the worker starts the job. Depending on timing, a partial cancellation fee may apply as outlined in our policy.',
  'faq_cat_all': 'All Articles',
  'faq_cat_payment': 'Payment',
  'faq_cat_verification': 'Verification',
  'faq_cat_disputes': 'Disputes',
  'faq_cat_safety': 'Safety',
  'ticket_cat_payment': 'Payment & Escrow',
  'ticket_cat_verification': 'Verification',
  'ticket_cat_disputes': 'Disputes',
  'ticket_cat_account': 'Account',
  'ticket_cat_tech': 'Technical Issue',
  'ticket_cat_other': 'Other',
  'chat_welcome_msg': 'Hello! Welcome to Support. How can we help you today?',
  'chat_time_just_now': 'Just now',
  'chat_time_now': 'Now',
  'chat_auto_reply': 'Thanks for reaching out, one of our agents will respond shortly.',
  'ticket_missing_title': 'Missing details',
  'ticket_missing_msg': 'Please fill in subject and message.',
  'ticket_submitted_title': 'Ticket submitted',
  'ticket_submitted_msg': 'Our support team will get back to you soon.',
  'worker_profile_oops_title': 'Oops!',
  'worker_profile_name_empty_error': 'Name cannot be empty.',
  'worker_profile_saving_loader': 'Saving...',
  'worker_profile_update_failed_title': 'Update Failed',
  'worker_profile_success_title': 'Success',
  'worker_profile_updated_success_message': 'Profile updated successfully!',
  'worker_profile_generic_error': 'Something went wrong, please try again.',
  'worker_profile_add_name_placeholder': 'Add your name',
  'worker_profile_not_provided': 'Not provided',
  'worker_profile_im_a_role': "I'm a @role",
  'worker_lang_title': 'Choose your language',
  'worker_lang_eng_sub': 'ENGLISH',
  'worker_lang_uzb_sub': 'UZBEK',
  'worker_lang_rus_sub': 'RUSSIAN',
  'wallet_success_title': 'Success',
  'wallet_deposit_success_message': 'Deposit of @amount successful',
  'wallet_insufficient_balance_title': 'Insufficient Balance',
  'wallet_insufficient_balance_message': "You don't have enough funds to withdraw",
  'wallet_withdraw_success_message': 'Withdrawal completed successfully',
  'worker_profile_title': 'Profile',
  'worker_profile_online': 'ONLINE',
  'worker_profile_offline': 'OFFLINE',
  'worker_profile_personal_info': 'Personal Info',
  'worker_profile_wallet': 'Wallet',
  'worker_profile_favourites': 'Favourites',
  'worker_profile_location': 'Location',
  'worker_profile_location_sub': 'Active for nearby jobs',
  'worker_profile_settings': 'Settings',
  'worker_profile_help_support': 'Help & Support',
  'worker_profile_logout': 'Logout',
  'worker_profile_logout_title': 'Logout',
  'worker_profile_logout_subtitle': 'Are you sure you want to logout?',
  'deposit_popup_title': 'Deposit Funds',
  'deposit_popup_select_card_type': 'SELECT CARD TYPE',
  'deposit_popup_label_amount': 'AMOUNT (\$)',
  'deposit_popup_hint_amount': '\$ 50.00',
  'deposit_popup_label_card_number': 'CARD NUMBER',
  'deposit_popup_hint_card_number': '8600 **** **** ****',
  'deposit_popup_top_text_card_number': 'UZCARD (8600)',
  'deposit_popup_label_expiry': 'EXPIRY DATE',
  'deposit_popup_hint_expiry': 'MM/YY',
  'deposit_popup_label_cvv': 'CVV',
  'deposit_popup_hint_cvv': '***',
  'deposit_popup_label_cardholder_name': 'CARDHOLDER NAME',
  'deposit_popup_hint_cardholder_name': 'JOHN DOE',
  'deposit_popup_confirm_button': 'Confirm Deposit',
  'worker_settings_title': 'Settings',
  'worker_settings_language': 'Choose your language',
  'worker_settings_notifications': 'Notifications',
  'worker_settings_dark_mode': 'Dark Mode',
  'worker_settings_dark_mode_sub': 'Switch between light and dark',
  'worker_settings_become_client': 'Become a Client',
  'worker_settings_switch': 'Switch',
  'worker_settings_app_version': 'App Version',
  'worker_settings_version_val': '1.2.0 (Stable)',
  'worker_settings_acc_status': 'Account Status',
  'worker_settings_verified': 'Verified',
  'worker_settings_security': 'Security',
  'worker_settings_security_val': 'SSL/SMS Protected',
  'withdraw_popup_title': 'Withdraw Funds',
  'withdraw_popup_method_card': 'Card',
  'withdraw_popup_method_bank_account': 'Bank Account',
  'withdraw_popup_label_amount': 'AMOUNT (\$)',
  'withdraw_popup_available_balance': 'AVAILABLE: @amount',
  'withdraw_popup_hint_amount': '\$ 100.00',
  'withdraw_popup_label_iban': 'BANK ACCOUNT (IBAN)',
  'withdraw_popup_hint_iban': 'UZ99 4321 0000 1234 5678',
  'withdraw_popup_confirm_button': 'Confirm Withdrawal',
  'worker_wallet_title': 'Wallet',
  'worker_wallet_recent_transactions': 'Recent Transactions',
  'worker_wallet_see_all': 'See All',
  'worker_wallet_total_balance': 'Total Balance',
  'worker_wallet_deposit_button': '+ Deposit',
  'worker_wallet_withdraw_button': '- Withdraw',
  'worker_wallet_tx_plumbing_title': 'Payment for Plumbing',
  'worker_wallet_tx_bank_withdrawal_title': 'Withdrawal to Bank',
  'worker_wallet_tx_hvac_title': 'Payment for HVAC',
  'worker_wallet_tx_time_today': 'Today, 2:30 PM',
  'worker_wallet_tx_time_yesterday': 'Yesterday, 4:15 PM',
  'worker_wallet_tx_time_mar5': 'Mar 5, 11:20 AM',
  'worker_personal_info_title': 'Personal Info',
  'worker_personal_info_full_name_label': 'FULL NAME',
  'worker_personal_info_email_label': 'EMAIL ADDRESS',
  'worker_personal_info_phone_label': 'PHONE NUMBER',
  'worker_personal_info_skills_label': 'SKILLS',
  'worker_personal_info_no_skills': 'No skills added yet',
  'worker_personal_info_edit_button': 'Edit Profile',
  'worker_bottom_nav_home': 'Home',
  'worker_bottom_nav_chat': 'Chat',
  'worker_bottom_nav_my_jobs': 'My Jobs',
  'worker_bottom_nav_profile': 'Profile',
  'client_bottom_nav_home': 'Home',
  'client_bottom_nav_chat': 'Chat',
  'client_bottom_nav_my_jobs': 'My Jobs',
  'client_bottom_nav_profile': 'Profile',
  'role_selection_title_line1': 'What Are You',
  'role_selection_title_line2': 'Looking For',
  'role_selection_post_job': 'Post A Job',
  'role_selection_find_work': 'Find A Work',
  'role_selection_continue': 'Continue',
  'role_selection_error_title': 'Error',
  'role_selection_error_message': 'Please select a role to continue',
  'languagesheettitle':'Choose your language',
  'languagesheetsubtitle':'You can change this anytime from Settings',
  'languagesheetloading':'Please wait...',
  'languagesheetcontinue':'Continue',
  "edit_profile_section_personal": "Personal Information",
  "edit_profile_email_locked_note": "Email cannot be changed",
  "edit_profile_btn_saving": "Saving...",
  "worker_edit_profile_section_personal": "Personal Information",
  "worker_edit_profile_email_locked_note": "Email cannot be changed",
  "worker_edit_profile_no_skills_yet": "No skills added yet",
  "worker_personal_info_section_contact": "Contact Information",
  "personal_info_section_contact": "Contact Information",
  "workersettingsnack":"Switched to",
  "post_job_image_pick_error_title": "Error",
  "post_job_image_pick_error_message": "Something went wrong while selecting the photo. Please try again."
};