Map<String, String> ruRU = {
  'common_continue': 'Продолжать',
  'onboarding_language_title': 'Добро пожаловать на работу',
  'onboarding_language_subtitle':
  'Революционный подход к поиску работы и сотрудников.',
  'auth_signup_login_title': 'Зарегистрироваться или войти',
  'auth_create_account': 'Зарегистрироваться',
  'auth_details_subtitle': 'Введите свои данные для доступа к учетной записи',
  'auth_phone_tab': 'Телефон',
  'auth_email_tab': 'Электронная почта',
  "auth_button_continue" : "Продолжить",
  'auth_button_loading' : 'Пожалуйста, подождите...',
  'auth_phone_hint': '+1 (555) 000-0000',
  'auth_email_hint': 'Введите адрес электронной почты',
  'auth_error_enter_phone': 'Пожалуйста, введите номер телефона.',
  'auth_error_valid_phone': 'Введите корректный номер телефона (10–15 цифр)',
  'auth_error_enter_email': 'Пожалуйста, введите свой адрес электронной почты.',
  'auth_error_valid_email': 'Введите действительный адрес электронной почты',
  'auth_error_general': 'Ошибка',
  'auth_error_something_wrong': 'Что-то пошло не так',
  'auth_error_invalid_response': 'Некорректный ответ от сервера',
  'auth_error_retry': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'auth_loader_wait': 'Пожалуйста, подождите...',
  'api_error_invalid_response': 'Некорректный ответ сервера',
  'api_error_something_wrong': 'Что-то пошло не так',
  'api_error_no_connection': 'Нет подключения к Интернету или сервер недоступен',
  'chat_error_load_list': 'Не удалось загрузить список чатов',
  'chat_error_load_messages': 'Не удалось загрузить сообщения',
  'chat_error_send_message': 'Не удалось отправить сообщение',
  'chat_error_no_response': 'От сервера не получен ответ',
  'chat_error_unexpected_response': 'Неожиданный ответ сервера',
  'chat_error_request_failed': 'Запрос не удался',
  'chat_ok': 'ХОРОШО',
  'profile_error_session_not_found': 'Сеанс пользователя не найден. Пожалуйста, войдите в систему снова.',
  'job_error_not_logged_in': "Вы не вошли в систему. Пожалуйста, войдите снова и повторите попытку.",
  'job_success_posted': 'Вакансия успешно опубликована!',
  'job_error_failed_post': 'Не удалось опубликовать вакансию. Пожалуйста, попробуйте еще раз.',
  'job_error_something_went_wrong': 'Что-то пошло не так. Пожалуйста, проверьте подключение и попробуйте снова.',
  'job_cancelled_success': 'Задание отменено.',
  'job_cancelled_unable': 'Не удалось отменить задание.',
  'job_confirmed_success': 'Задача успешно подтверждена.',
  'job_confirmed_unable': 'Не удалось подтвердить задание.',
  'job_select_worker_success': 'Рабочий успешно выбран.',
  'job_select_worker_unable': 'Не удалось выбрать работника.',
  'notif_error_not_logged_in': 'Пользователь не вошел в систему',
  'notif_error_server': 'Ошибка сервера',
  'notif_error_something_went_wrong': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'status_error_title': 'Ошибка',
  'status_error_update_failed': 'Не удалось обновить статус. Пожалуйста, попробуйте еще раз.',
  'status_loader_going_online': 'Выход в сеть...',
  'status_loader_going_offline': 'Выход из сети...',
  'status_snackbar_failed_title': 'Обновление не удалось',
  'online_status_empty_response': 'Пустой ответ от сервера.',
  'online_status_success_msg': 'Статус успешно обновлен!',
  'online_status_failed_msg': 'Не удалось обновить статус.',
  'online_status_error_connection': 'Что-то пошло не так. Пожалуйста, проверьте подключение к интернету.',
  'worker_job_applied_success': 'Заявка успешно подана!',
  'worker_job_complete_success': 'Задание отмечено как выполненное.',
  'worker_job_complete_unable': 'Не удалось завершить задание.',
  'worker_job_confirm_success': 'Успешно подтверждено.',
  'worker_job_confirm_unable': 'Не удалось подтвердить.',
  'worker_job_error_something_went_wrong': 'Что-то пошло не так. Пожалуйста, проверьте подключение и попробуйте снова.',
  'dialog_logout_title': 'Выйти',
  'dialog_logout_subtitle': 'Вы уверены, что хотите выйти?',
  'dialog_delete_title': 'Удалить',
  'dialog_delete_subtitle': 'Это действие нельзя отменить',
  'dialog_default_logout_title': 'Выйти',
  'dialog_default_logout_subtitle': 'Вы уверены, что хотите выйти?',
  'dialog_default_confirm_text': 'Выйти',
  'dialog_default_cancel_text': 'Отмена',
  'error_default_title': 'Ошибка',
  'success_default_title': 'Успех',
  'info_default_title': 'Информация',
  'image_picker_title': 'Выберите фото профиля',
  'image_picker_camera': 'Камера',
  'image_picker_gallery': 'Галерея',
  'custom_text_field_search_hint': 'Поиск...',
  'otp_error_complete_code': 'Пожалуйста, введите полный 6-значный код',
  'otp_verifying': 'Проверка...',
  'otp_default_invalid': 'Неверный код подтверждения',
  'otp_error_invalid_response': 'Некорректный ответ от сервера',
  'otp_error_account_blocked_title': 'Аккаунт заблокирован',
  'otp_error_account_blocked_subtitle': 'Ваш аккаунт был заблокирован. Пожалуйста, свяжитесь со службой поддержки.',
  'otp_resend_success_title': 'Отправлено',
  'otp_resend_success_msg': 'Новый код подтверждения отправлен.',
  'otp_resend_error_msg': 'Не удалось повторно отправить код',
  'otp_error_something_went_wrong': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'otp_error_default': 'Ошибка',
  'otp_screen_title': 'Проверка кода',
  'otp_screen_subtitle': 'Введите 6-значный код, отправленный на\n@contact',
  'otp_screen_resending': 'Повторная отправка...',
  'otp_screen_resend_prompt': "Не получили код? Отправить повторно",
  'otp_screen_button_verifying': 'Проверка...',
  'otp_screen_button_verify': 'Подтвердить',
  'job_card_flexible': 'ГИБКО',
  'job_card_attributes': 'ХАРАКТЕРИСТИКИ',
  'job_card_posted_prefix': 'Опубликовано ',
  'job_card_see_detail': 'Подробнее',
  'client_confirm_worker_selecting': 'Выбор работника...',
  'client_confirm_worker_selected_title': 'Работник выбран',
  'client_confirm_worker_action_failed_title': 'Действие не выполнено',
  'client_confirm_worker_cancelling': 'Отмена задания...',
  'client_confirm_worker_cancelled_title': 'Задание отменено',
  'client_confirm_worker_completing': 'Отметка задания как выполненного...',
  'client_confirm_worker_completed_title': 'Задание выполнено',
  'client_confirm_worker_header_title': 'Профиль работника',
  'client_confirm_worker_skills': 'Навыки',
  'client_confirm_worker_job_budget': 'Бюджет задания',
  'client_confirm_worker_payment_via': 'Оплата через @mode',
  'client_confirm_worker_completed_banner': 'Это задание отмечено как выполненное.',
  'client_confirm_worker_cancelled_banner': 'Это задание было отменено.',
  'client_confirm_worker_chat_button': 'Написать работнику',
  'client_confirm_worker_unavailable': 'Недоступно',
  'client_confirm_worker_cancel_job': 'Отменить задание',
  'client_confirm_worker_accept_worker': 'Принять работника',
  'client_confirm_worker_mark_completed': 'Отметить как выполненное',
  'client_confirm_worker_active_strike': '@count активное нарушение',
  'client_confirm_worker_active_strikes': '@count активных нарушений',
  'client_confirm_worker_applied_for': 'Подал заявку на',
  'client_jobs_error_loading': 'Не удалось загрузить ваши задания. Потяните вниз, чтобы повторить попытку.',
  'client_jobs_tab_all': 'Все',
  'client_home_welcome': 'Добро пожаловать',
  'client_home_discover_jobs': 'Найти задания',
  'client_home_subtitle': 'Все ваши опубликованные задания в одном месте',
  'client_home_no_jobs': 'В этой категории пока нет доступных заданий.',
  'client_home_your_posted_jobs': 'Ваши опубликованные задания',
  'client_home_online': 'В СЕТИ',
  'client_home_offline': 'НЕ В СЕТИ',
  'client_home_wallet': 'КОШЕЛЕК',
  'client_home_active_jobs': 'АКТИВНЫЕ ЗАДАНИЯ',
  'client_home_retry': 'Повторить',
  'model_worker_unknown': 'Неизвестный работник',
  'model_worker_rating_new': 'Новый',
  'model_job_general': 'Общее',
  'model_job_untitled': 'Задание без названия',
  'model_job_urgency_urgent': 'Срочно',
  'model_job_urgency_critical': 'Критично',
  'model_job_urgency_flexible': 'Гибко',
  'model_job_urgency_normal': 'Обычно',
  'model_job_priority': 'ПРИОРИТЕТ',
  'model_job_budget_hourly': 'Почасовая ставка',
  'model_job_budget_negotiable': 'По договоренности',
  'model_job_budget_fixed': 'Фиксированная цена',
  'model_job_budget_hourly_suffix': '/час',
  'model_job_budget_hourly_label': 'Почасово',
  'model_job_budget_to_be_discussed': 'Обсуждается в чате',
  'model_job_budget_one_time': ' (единоразово)',
  'model_job_payment_card': 'Карта',
  'model_job_payment_cash': 'Наличные',
  'model_job_payment_wallet': 'Кошелек',
  'model_job_payment_escrow': 'Эскроу',
  'model_job_payment_commission': 'Только комиссия',
  'model_job_payment_not_specified': 'Не указано',
  'model_job_datetype_custom': 'Другая дата',
  'model_job_datetype_today': 'Сегодня',
  'job_detail_loading_applicants': 'Загрузка кандидатов...',
  'job_detail_refreshing': 'Обновление...',
  'job_detail_not_found': 'Задание не найдено',
  'job_detail_overview': 'Обзор',
  'job_detail_category': 'Категория',
  'job_detail_subcategory': 'Подкатегория',
  'job_detail_city': 'Город',
  'job_detail_location': 'Местоположение',
  'job_detail_status': 'Статус',
  'job_detail_budget_payment': 'Бюджет и оплата',
  'job_detail_budget_type': 'Тип бюджета',
  'job_detail_amount': 'Сумма',
  'job_detail_payment_mode': 'Способ оплаты',
  'job_detail_schedule': 'Расписание',
  'job_detail_date': 'Дата',
  'job_detail_start_time': 'Время начала',
  'job_detail_end_time': 'Время окончания',
  'job_detail_date_type': 'Тип даты',
  'job_detail_description': 'Описание',
  'job_detail_no_description': 'Описание не предоставлено.',
  'job_detail_attributes': 'Характеристики',
  'job_detail_interested_worker': 'Заинтересованный работник',
  'job_detail_no_applicants_yet': 'Пока никто не подал заявку',
  'job_detail_worker_applied': '@count работник(ов) подали заявку на это задание',
  'job_detail_assigned_banner': 'Работник уже назначен на это задание.',
  'job_detail_photos': 'Фотографии',
  'job_detail_photo_count_single': '@count фото',
  'job_detail_photo_count_plural': '@count фото',
  'job_detail_see_detail': 'Подробнее',
  'job_detail_online': 'В сети',
  'job_detail_offline': 'Не в сети',
  'job_detail_strike_single': '@count нарушение',
  'job_detail_strike_plural': '@count нарушений',
  'job_detail_no_workers_applied': 'Пока ни один работник не подал заявку',
  'client_my_job_tab_active': 'Активные',
  'client_my_job_tab_completed': 'Завершенные',
  'client_my_job_tab_cancelled': 'Отмененные',
  'client_my_jobs_title': 'Мои задания',
  'client_my_jobs_empty_prefix': 'Нет ',
  'client_my_jobs_empty_suffix': ' заданий',
  'client_my_jobs_location_fallback': 'Удаленное расположение',
  'client_my_jobs_date_fallback': 'Н/Д',
  'client_my_jobs_title_fallback': 'Без названия',
  'client_my_jobs_desc_fallback': 'Описание недоступно.',
  'client_my_jobs_budget_fixed': 'Фиксированный',
  'edit_profile_title': 'Редактировать профиль',
  'edit_profile_change_photo': 'Изменить фото',
  'edit_profile_hint_name': 'Полное имя',
  'edit_profile_hint_email': 'Адрес электронной почты',
  'edit_profile_email_fallback': 'Не зарегистрировано с электронной почтой',
  'edit_profile_hint_phone': 'Номер телефона',
  'edit_profile_btn_cancel': 'Отмена',
  'edit_profile_btn_save': 'Сохранить изменения',
  'favourites_title_my': 'Мои ',
  'favourites_title_highlight': 'Избранное',
  'favourites_saved_jobs_count': '@count сохраненных заданий',
  'favourites_empty_title': 'Пока нет избранного',
  'favourites_empty_subtitle': 'Нажмите на значок закладки на любом задании,\nчтобы сохранить его здесь на потом.',
  'help_support_tab_faqs': 'Частые вопросы',
  'help_support_tab_submit_ticket': 'Отправить обращение',
  'help_support_tab_live_chat': 'Онлайн-чат',
  'help_support_title': 'Помощь и поддержка',
  'help_support_live_badge': '24/7 НА СВЯЗИ',
  'help_support_kb_section_title': 'БАЗА ЗНАНИЙ И ЧАСТЫЕ ВОПРОСЫ',
  'help_support_no_results': 'Результаты не найдены',
  'help_support_direct_assistance_title': 'ПРЯМАЯ ПОДДЕРЖКА',
  'help_support_call_label': 'ПОЗВОНИТЬ В ПОДДЕРЖКУ',
  'help_support_email_label': 'НАПИШИТЕ НАМ',
  'help_support_search_hint': 'Поиск ответов, руководств...',
  'help_support_category_label': 'Категория',
  'help_support_select_category_hint': 'Выберите категорию',
  'help_support_subject_label': 'Тема',
  'help_support_subject_hint': 'Краткое описание проблемы...',
  'help_support_message_label': 'Подробное сообщение',
  'help_support_message_hint': 'Укажите все важные детали вашего обращения...',
  'help_support_submit_ticket_button': 'Отправить обращение',
  'help_support_ai_name': 'ИИ-поддержка Uybor',
  'help_support_online_operator': 'ОПЕРАТОР НА СВЯЗИ',
  'help_support_chat_input_hint': 'Введите ваш вопрос...',
  'faq_question_escrow': 'Как работает система эскроу-платежей?',
  'faq_answer_escrow': 'Когда вы нанимаете работника, ваш платеж надежно удерживается в эскроу и переводится ему только после того, как задание отмечено выполненным и одобрено вами.',
  'faq_category_payment': 'Оплата',
  'faq_question_fees': 'Есть ли комиссия за регистрацию?',
  'faq_answer_fees': 'Создание аккаунта и использование платформы полностью бесплатны. Небольшая комиссия взимается только при успешном завершении задания.',
  'faq_question_badges': 'Как работают значки верификации работников?',
  'faq_answer_badges': 'Работники получают значки верификации после предоставления действительных документов и прохождения проверки, что помогает вам нанимать с уверенностью.',
  'faq_category_verification': 'Верификация',
  'faq_question_dispute': 'Что делать, если возник спор?',
  'faq_answer_dispute': 'Откройте обращение в поддержку на вкладке «Отправить обращение» с деталями разногласия. Наша команда рассмотрит случай и поможет найти справедливое решение.',
  'faq_category_disputes': 'Споры',
  'faq_question_data': 'Как защищены мои личные данные?',
  'faq_answer_data': 'Все личные данные шифруются при передаче и хранении и никогда не передаются третьим лицам без вашего явного согласия.',
  'faq_category_safety': 'Безопасность',
  'faq_question_cancel': 'Могу ли я отменить задание после внесения гарантийного депозита?',
  'faq_answer_cancel': 'Да, вы можете отменить задание до того, как работник начнет его выполнение. В зависимости от сроков может взиматься частичная комиссия за отмену согласно нашим правилам.',
  'faq_cat_all_articles': 'Все статьи',
  'ticket_cat_payment_escrow': 'Оплата и эскроу',
  'ticket_cat_verification': 'Верификация',
  'ticket_cat_disputes': 'Споры',
  'ticket_cat_account': 'Аккаунт',
  'ticket_cat_technical': 'Техническая проблема',
  'ticket_cat_other': 'Другое',
  'support_chat_welcome': 'Здравствуйте! Добро пожаловать в поддержку. Чем мы можем вам помочь сегодня?',
  'support_chat_time_just_now': 'Только что',
  'support_chat_time_now': 'Сейчас',
  'support_chat_auto_reply': 'Спасибо за обращение, один из наших специалистов скоро ответит.',
  'support_snackbar_missing_title': 'Не хватает данных',
  'support_snackbar_missing_msg': 'Пожалуйста, заполните тему и сообщение.',
  'support_snackbar_success_title': 'Обращение отправлено',
  'support_snackbar_success_msg': 'Наша команда поддержки скоро свяжется с вами.',
  'profile_fetch_error_title': 'Ошибка',
  'profile_update_missing_name': 'Имя не может быть пустым.',
  'profile_update_missing_name_title': 'Упс!',
  'profile_update_loader': 'Сохранение...',
  'profile_update_failed_title': 'Обновление не удалось',
  'profile_update_fallback_error': 'Что-то пошло не так, пожалуйста, попробуйте еще раз.',
  'profile_update_success_title': 'Успех',
  'profile_update_success_msg': 'Профиль успешно обновлен!',
  'profile_skill_empty_title': 'Упс!',
  'profile_skill_empty_msg': 'Название навыка не может быть пустым.',
  'profile_skill_exists_title': 'Уже добавлено',
  'profile_skill_exists_msg': 'Этот навык уже есть в вашем списке.',
  'profile_fallback_name': 'Добавьте ваше имя',
  'profile_fallback_email': 'Не указано',
  'profile_fallback_phone': 'Не указано',
  'profile_role_client': 'Клиент',
  'profile_role_worker': 'Работник',
  'profile_role_prefix': "Я — @role",
  'client_profile_title': 'Профиль',
  'client_profile_online': 'В СЕТИ',
  'client_profile_offline': 'НЕ В СЕТИ',
  'client_profile_personal_info': 'Личная информация',
  'client_profile_wallet': 'Кошелек',
  'client_profile_favourites': 'Избранное',
  'client_profile_location': 'Местоположение',
  'client_profile_location_subtitle': 'Активно для заданий поблизости',
  'client_profile_settings': 'Настройки',
  'client_profile_help_support': 'Помощь и поддержка',
  'client_profile_logout': 'Выйти',
  'client_profile_logout_confirm': 'Вы уверены, что хотите выйти?',
  'settings_title': 'Настройки',
  'settings_lang_title': 'Выберите язык',
  'settings_notifications_title': 'Уведомления',
  'settings_dark_mode_title': 'Темная тема',
  'settings_dark_mode_subtitle': 'Переключение между светлой и темной темой',
  'settings_become_worker_title': 'Стать работником',
  'settings_switch_btn': 'Переключить',
  'settings_info_version_key': 'Версия приложения',
  'settings_info_version_val': '1.2.0 (Стабильная)',
  'settings_info_status_key': 'Статус аккаунта',
  'settings_info_status_val': 'Подтвержден',
  'settings_info_security_key': 'Безопасность',
  'settings_info_security_val': 'Защищено SSL/SMS',
  'settings_logout_loader': 'Выход из системы...',
  'settings_logout_error_title': 'Ошибка',
  'settings_logout_error_msg': 'Не удалось выйти. Пожалуйста, попробуйте еще раз.',
  'settings_ctrl_err_session_title': 'Ошибка',
  'settings_ctrl_err_session_msg': 'Сеанс пользователя не найден.',
  'settings_ctrl_loader_switching': 'Переключение режима...',
  'settings_ctrl_success_title': 'Успех',
  'settings_ctrl_success_msg': 'Режим успешно переключен',
  'settings_ctrl_err_switch': 'Не удалось переключить роль',
  'settings_ctrl_err_general': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'settings_ctrl_loader_logout': 'Выход из системы...',
  'settings_ctrl_err_logout': 'Не удалось выйти. Пожалуйста, попробуйте еще раз.',
  'wallet_title': 'Кошелек',
  'wallet_balance_title': 'Общий баланс',
  'wallet_recent_tx': 'Последние транзакции',
  'wallet_see_all': 'Смотреть все',
  'wallet_btn_deposit': '+ Пополнить',
  'wallet_btn_withdraw': '- Вывести',
  'wallet_tx_plumbing': 'Оплата за сантехнику',
  'wallet_tx_withdrawal': 'Вывод на банковский счет',
  'wallet_tx_hvac': 'Оплата за отопление и вентиляцию',
  'wallet_tx_time_today': 'Сегодня, 14:30',
  'wallet_tx_time_yesterday': 'Вчера, 16:15',
  'wallet_tx_time_old': '5 марта, 11:20',
  'wallet_ctrl_success_title': 'Успех',
  'wallet_ctrl_deposit_msg': 'Пополнение на \$%s выполнено успешно',
  'wallet_ctrl_err_balance_title': 'Недостаточно средств',
  'wallet_ctrl_err_balance_msg': 'У вас недостаточно средств для вывода',
  'wallet_ctrl_withdraw_msg': 'Вывод средств успешно выполнен',
  'deposit_title': 'Пополнить счет',
  'deposit_select_card': 'ВЫБЕРИТЕ ТИП КАРТЫ',
  'deposit_label_amount': 'СУММА (\$)',
  'deposit_hint_amount': '\$ 50.00',
  'deposit_label_card_num': 'НОМЕР КАРТЫ',
  'deposit_hint_card_num': '8600 **** **** ****',
  'deposit_top_uzcard': 'UZCARD (8600)',
  'deposit_label_expiry': 'СРОК ДЕЙСТВИЯ',
  'deposit_hint_expiry': 'ММ/ГГ',
  'deposit_label_cvv': 'CVV',
  'deposit_hint_cvv': '***',
  'deposit_label_name': 'ИМЯ ВЛАДЕЛЬЦА КАРТЫ',
  'deposit_hint_name': 'ИВАН ИВАНОВ',
  'deposit_btn_confirm': 'Подтвердить пополнение',
  'withdraw_title': 'Вывести средства',
  'withdraw_amount_label': 'СУММА (\$)',
  'withdraw_available_prefix': 'ДОСТУПНО: \$',
  'withdraw_hint_amount': '\$ 100.00',
  'withdraw_bank_label': 'БАНКОВСКИЙ СЧЕТ (IBAN)',
  'withdraw_hint_iban': 'UZ99 4321 0000 1234 5678',
  'withdraw_btn_confirm': 'Подтвердить вывод',
  'post_job_title_post_a': 'Разместить ',
  'post_job_title_task': 'задание',
  'post_job_subtitle': 'Найдите нужного специалиста для вашей работы',
  'post_job_task_title_label': 'Название задания',
  'post_job_task_title_hint': 'например, помощь в переноске дивана',
  'post_job_category_label': 'Категория',
  'post_job_select_category_default': 'Выберите\nкатегорию',
  'post_job_subcategory_label': 'Подкатегория',
  'post_job_select_subcategory_default': 'Выберите\nподкатегорию',
  'post_job_select_category_sheet_title': 'Выберите категорию',
  'post_job_select_subcategory_sheet_title': 'Выберите подкатегорию',
  'post_job_all_subcategories': 'Все подкатегории',
  'post_job_location_label': 'Местоположение и адрес',
  'post_job_location_hint': 'например, ул. Парковая 45, Ташкент',
  'post_job_description_label': 'Описание',
  'post_job_description_hint': 'Опишите требования и объем работы...',
  'post_job_budget_title': 'Бюджет',
  'post_job_budget_subtitle_fixed': 'Единоразовая полная оплата',
  'post_job_budget_subtitle_hourly': 'Оплата за фактически отработанные часы',
  'post_job_budget_subtitle_negotiable': 'Цена обсуждается и согласовывается напрямую с работником',
  'post_job_tab_fixed_price': 'Фиксир.\nцена',
  'post_job_tab_hourly_rate': 'Почасовая\nставка',
  'post_job_tab_negotiable': 'По договоренности',
  'post_job_amount_label': 'Сумма',
  'post_job_currency_uzs': 'UZS',
  'post_job_amount_hint': '100',
  'post_job_payment_type_label': 'Способ оплаты',
  'post_job_rate_per_hour_label': 'Ставка в час',
  'post_job_rate_hint': '25',
  'post_job_estimated_hours_label': 'Ожидаемые часы',
  'post_job_optional': '(Необязательно)',
  'post_job_hours_hint': '4',
  'post_job_negotiable_budget_title': 'Договорной бюджет',
  'post_job_negotiable_budget_desc': 'Бюджет будет обсужден и согласован с работником в чате.',
  'post_job_payment_cash': 'Наличные',
  'post_job_payment_card': 'Карта',
  'post_job_payment_wallet': 'Кошелек',
  'post_job_schedule_badge': 'Расписание',
  'post_job_select_start_time_title': 'Выберите время начала',
  'post_job_select_start_time_message': 'Пожалуйста, сначала выберите время начала',
  'post_job_start_time_label': 'Время начала',
  'post_job_end_time_label': 'Время окончания',
  'post_job_choose_date_label': 'Выберите дату',
  'post_job_today': 'Сегодня',
  'post_job_custom_date': 'Другая дата...',
  'post_job_urgency_label': 'Срочность',
  'post_job_urgent': 'Срочно',
  'post_job_flexible': 'Гибко',
  'post_job_photo_attachment_label': 'Прикрепить фото',
  'post_job_drag_drop_photos': 'Перетащите фото или нажмите для выбора',
  'post_job_photos_limit_hint': 'До 3 фото, JPG или PNG',
  'post_job_cancel_button': 'Отмена',
  'post_job_submit_button': 'Отправить',
  'personal_info_title': 'Личная информация',
  'personal_info_label_name': 'ПОЛНОЕ ИМЯ',
  'personal_info_label_email': 'АДРЕС ЭЛЕКТРОННОЙ ПОЧТЫ',
  'personal_info_label_phone': 'НОМЕР ТЕЛЕФОНА',
  'personal_info_btn_edit': 'Редактировать профиль',
  // Delivery & Logistics
  'category_delivery': 'Доставка и логистика',
  'category_sub_small_item': 'Доставка мелких предметов и посылок',
  'category_sub_grocery': 'Доставка продуктов и еды',
  'category_sub_heavy_freight': 'Тяжелые грузы и перевозки',
  'category_sub_document': 'Курьерская доставка документов',

  // Handyman & Repairs
  'category_handyman': 'Мастер на час и ремонт',
  'category_sub_plumbing': 'Сантехнический ремонт',
  'category_sub_electrical': 'Электромонтажные работы',
  'category_sub_furniture': 'Сборка мебели',
  'category_sub_carpentry': 'Столярные и плотницкие работы',
  'category_sub_painting': 'Покраска и гипсокартон',
  'category_sub_appliance': 'Установка и ремонт техники',

  // Cleaning Services
  'category_cleaning': 'Клининговые услуги',
  'category_sub_house_clean': 'Уборка дома и квартиры',
  'category_sub_deep_clean': 'Генеральная уборка и уборка при выезде',
  'category_sub_laundry': 'Стирка и глажка',
  'category_sub_window_clean': 'Мытье окон и стекол',
  'category_sub_carpet_clean': 'Чистка ковров и мягкой мебели',

  // Moving & Storage
  'category_moving': 'Переезд и хранение',
  'category_sub_local_move': 'Местный переезд и перевозка',
  'category_sub_packing': 'Помощь с упаковкой и распаковкой',
  'category_sub_heavy_lifting': 'Тяжелая переноска и погрузка',
  'category_sub_office_move': 'Офисный и коммерческий переезд',

  // Pet Care
  'category_pet_care': 'Уход за питомцами',
  'category_sub_pet_sitting': 'Присмотр и передержка питомцев',
  'category_sub_dog_walking': 'Выгул собак',
  'category_sub_pet_grooming': 'Груминг и купание питомцев',
  'category_sub_pet_training': 'Дрессировка и коррекция поведения питомцев',

  // Tech & IT Support
  'category_tech_it': 'Техническая и ИТ-поддержка',
  'category_sub_computer_repair': 'Ремонт компьютеров и ноутбуков',
  'category_sub_smart_home': 'Настройка умного дома и Wi-Fi',
  'category_sub_phone_repair': 'Ремонт телефонов и планшетов',
  'category_sub_tv_mounting': 'Установка телевизора и аудиосистемы',

  // Beauty & Wellness
  'category_beauty_wellness': 'Красота и здоровье',
  'category_sub_haircut_styling': 'Стрижка и укладка',
  'category_sub_makeup': 'Макияж и услуги красоты',
  'category_sub_massage': 'Массаж и спа-процедуры',
  'category_sub_nail_care': 'Маникюр и педикюр',

  // Events & Photography
  'category_events_photo': 'Мероприятия и фотография',
  'category_sub_event_photography': 'Фотосъемка мероприятий и портретов',
  'category_sub_catering': 'Кейтеринг и выпечка',
  'category_sub_event_planning': 'Организация вечеринок и мероприятий',
  'category_sub_dj_music': 'DJ и живая музыка',

  // Automotive Services
  'category_automotive': 'Автомобильные услуги',
  'category_sub_mobile_mechanic': 'Выездной автомеханик и диагностика',
  'category_sub_car_wash': 'Выездная мойка и детейлинг',
  'category_sub_jump_start': 'Прикуривание аккумулятора и эвакуация',

  // Gardening & Outdoor
  'category_gardening': 'Садоводство и придомовая территория',
  'category_sub_lawn_mowing': 'Стрижка газона и уход за двором',
  'category_sub_landscaping': 'Ландшафтный дизайн и озеленение',
  'category_sub_snow_removal': 'Уборка снега и антигололедная обработка',
  'category_sub_pool_maintenance': 'Обслуживание и чистка бассейна',

  // Lessons & Tutoring
  'category_lessons_tutoring': 'Уроки и репетиторство',
  'category_sub_academic_tutoring': 'Репетиторство по учебным предметам и математике',
  'category_sub_language_lessons': 'Языковые уроки',
  'category_sub_music_lessons': 'Уроки музыки и игры на инструментах',
  'category_sub_fitness_training': 'Персональные фитнес-тренировки',

  // Business & Admin
  'category_business_admin': 'Бизнес и административная поддержка',
  'category_sub_virtual_assistant': 'Услуги виртуального ассистента',
  'category_sub_data_entry': 'Ввод данных и набор текста',
  'category_sub_translation': 'Перевод документов',
  'category_sub_graphic_design': 'Графический дизайн и брендинг',
  // post job controller
  'post_job_time_placeholder': '--:--',
  'post_job_photo_limit_title': 'Достигнут лимит',
  'post_job_photo_limit_message': 'Вы можете прикрепить не более 3 фотографий',
  'post_job_validation_missing_title_title': 'Не указано название',
  'post_job_validation_missing_title_message': 'Пожалуйста, введите название задания',
  'post_job_validation_missing_category_title': 'Не выбрана категория',
  'post_job_validation_missing_category_message': 'Пожалуйста, выберите категорию',
  'post_job_validation_missing_subcategory_title': 'Не выбрана подкатегория',
  'post_job_validation_missing_subcategory_message': 'Пожалуйста, выберите подкатегорию',
  'post_job_validation_missing_location_title': 'Не указано местоположение',
  'post_job_validation_missing_location_message': 'Пожалуйста, введите местоположение',
  'post_job_validation_missing_description_title': 'Не указано описание',
  'post_job_validation_missing_description_message': 'Пожалуйста, опишите задание',
  'post_job_validation_missing_amount_title': 'Не указана сумма',
  'post_job_validation_missing_amount_message': 'Пожалуйста, введите сумму бюджета',
  'post_job_validation_missing_rate_title': 'Не указана ставка',
  'post_job_validation_missing_rate_message': 'Пожалуйста, введите почасовую ставку',
  'post_job_validation_missing_start_time_title': 'Не указано время начала',
  'post_job_validation_missing_start_time_message': 'Пожалуйста, выберите время начала',
  'post_job_validation_missing_end_time_title': 'Не указано время окончания',
  'post_job_validation_missing_end_time_message': 'Пожалуйста, выберите время окончания',
  'post_job_success_title': 'Успех',
  'post_job_failed_title': 'Ошибка',
  'nav_home': 'Главная',
  'nav_chat': 'Чат',
  'nav_my_jobs': 'Мои задания',
  'nav_profile': 'Профиль',
  'post_job_summary_header_review': 'Проверка и ',
  'post_job_summary_header_confirm': 'подтверждение',
  'post_job_summary_header_subtitle': 'Пожалуйста, проверьте все перед публикацией',
  'post_job_summary_task_details_title': 'Детали задания',
  'post_job_summary_title_label': 'Название',
  'post_job_summary_subcategory_label': 'Подкатегория',
  'post_job_summary_location_label': 'Местоположение',
  'post_job_summary_budget_payment_title': 'Бюджет и оплата',
  'post_job_summary_budget_type_label': 'Тип бюджета',
  'post_job_summary_date_label': 'Дата',
  'post_job_summary_budget_fixed_price': 'Фиксированная цена',
  'post_job_summary_budget_hourly_rate': 'Почасовая ставка',
  'post_job_summary_budget_negotiable': 'По договоренности',
  'post_job_summary_amount_one_time': '(единоразово)',
  'post_job_summary_amount_per_hour': '/ час',
  'post_job_summary_amount_hrs_suffix': 'ч',
  'post_job_summary_amount_negotiable_desc': 'Обсуждается в чате',
  'post_job_summary_edit_details_button': 'Редактировать детали',
  'post_job_summary_confirm_submit_button': 'Подтвердить и отправить',
  'role_ctrl_err_title': 'Ошибка выбора',
  'role_ctrl_err_msg': 'Пожалуйста, выберите роль, чтобы продолжить.',
  'tab_all': 'Все',
  'tab_pending': 'В ожидании',
  'tab_ongoing': 'Непрерывный',
  'tab_completed': 'Завершенный',
  'tab_cancelled': 'Отменено',
  'chat_list_title': 'Сообщения',
  'chat_list_search_hint': 'Поиск чатов...',
  'chat_list_no_conversations': 'Пока нет диалогов',
  'chat_tile_no_message': 'Пока нет сообщений',
  'chat_controller_error_title': 'Ошибка',
  'chat_controller_session_expired': 'Сеанс входа не найден, пожалуйста, войдите снова.',
  'message_screen_error_title': 'Ошибка',
  'message_screen_send_failed_title': 'Не удалось отправить сообщение',
  'message_screen_empty_state': 'Пока нет сообщений. Отправьте первое сообщение, чтобы начать диалог.',
  'message_screen_voice_message': 'Голосовое сообщение',
  'message_screen_input_hint': 'Введите сообщение...',
  'notification_time_just_now': 'ТОЛЬКО ЧТО',
  "notification_screen_mark_all_read":"Читать всё",
  'notification_time_min_ago': 'МИН НАЗАД',
  'notification_time_hour_ago': 'Ч НАЗАД',
  'notification_time_day_ago': 'Д НАЗАД',
  'notification_time_month_ago': 'МЕС НАЗАД',
  'notification_time_year_ago': 'ГОД НАЗАД',
  'notification_screen_title': 'Уведомления',
  'notification_screen_tab_inbox': 'Входящие',
  'notification_screen_tab_settings': 'Настройки',
  'notification_screen_load_error_fallback': 'Не удалось загрузить уведомления',
  'notification_screen_error_title': "Не удалось загрузить уведомления",
  'notification_screen_empty_title': 'Пока нет уведомлений',
  'notification_screen_empty_subtitle': "Мы сообщим вам, когда появится что-то новое.",
  'notification_screen_retry_button': 'Повторить',
  'notification_screen_push_title': 'Push-уведомления',
  'notification_screen_push_subtitle': 'Мгновенные оповещения',
  'notification_screen_email_title': 'Уведомления по электронной почте',
  'notification_screen_email_subtitle': 'Сообщения на почту',
  'notification_screen_sms_title': 'SMS-уведомления',
  'notification_screen_sms_subtitle': 'Обновления по SMS',
  'notification_screen_sound_title': 'Звуковые уведомления',
  'notification_screen_sound_subtitle': 'Звуковые эффекты приложения',
  'worker_active_jobs_title': 'Активные задания',
  'worker_active_jobs_empty': 'Сейчас нет активных заданий.',
  'worker_job_negotiable': 'По договоренности',
  'worker_job_not_specified': 'Не указано',
  'worker_job_payment_cash': 'Наличные',
  'worker_job_payment_card': 'Карта',
  'worker_job_payment_escrow': 'Эскроу',
  'worker_job_payment_commission': 'Только комиссия',
  'worker_job_client_fallback': 'Клиент',
  'worker_home_no_jobs_in_category': 'Сейчас нет заданий в категории @category.',
  'worker_home_city_required_title': 'Требуется город',
  'worker_home_city_required_message': 'Пожалуйста, укажите ваш город, чтобы увидеть доступные задания.',
  'worker_home_add_city_title': 'Добавьте ваш город',
  'worker_home_add_city_subtitle': 'Укажите свой город, чтобы мы могли показывать задания рядом с вами.',
  'worker_home_city_hint': 'например, Мультан, Лахор, Карачи',
  'worker_home_find_jobs_button': 'Найти задания',
  'worker_home_jobs_in_city': 'Задания в городе @city',
  'worker_home_swipe_subtitle': 'Пролистайте лучшие возможности',
  'worker_home_no_jobs_in_city': 'Сейчас нет доступных заданий в городе @city.',
  'worker_home_welcome': 'Добро пожаловать',
  'worker_home_online': 'В СЕТИ',
  'worker_home_offline': 'НЕ В СЕТИ',
  'worker_home_earnings_label': 'ДОХОД',
  'worker_home_active_label': 'АКТИВНО',
  'worker_job_card_selected': 'Работник выбран',
  'worker_job_card_see_detail': 'Подробнее',
  'worker_job_history_tab_all': 'Все',
  'worker_job_history_tab_active': 'Активные',
  'worker_job_history_tab_past': 'Прошлые','worker_job_detail_submitting_application': 'Отправка заявки...',
  'worker_job_detail_success_title': 'Успех',
  'worker_job_detail_application_update_title': 'Обновление заявки',
  'worker_job_detail_not_found': 'Задание не найдено',
  'worker_job_detail_cancelling_job': 'Отмена задания...',
  'worker_job_detail_job_cancelled_title': 'Задание отменено',
  'worker_job_detail_action_failed_title': 'Действие не выполнено',
  'worker_job_detail_marking_completed': 'Отметка задания как выполненного...',
  'worker_job_detail_job_completed_title': 'Задание выполнено',
  'worker_job_detail_overview_title': 'Обзор',
  'worker_job_detail_label_category': 'Категория',
  'worker_job_detail_label_city': 'Город',
  'worker_job_detail_label_location': 'Местоположение',
  'worker_job_detail_label_status': 'Статус',
  'worker_job_detail_budget_title': 'Бюджет и оплата',
  'worker_job_detail_label_amount': 'Сумма',
  'worker_job_detail_label_payment_mode': 'Способ оплаты',
  'worker_job_detail_schedule_title': 'Расписание',
  'worker_job_detail_label_date_time': 'Дата и время',
  'worker_job_detail_description_title': 'Описание',
  'worker_job_detail_no_description': 'Описание не предоставлено.',
  'worker_job_detail_posted_by_title': 'Опубликовано',
  'worker_job_detail_completed_banner': 'Вы отметили это задание как выполненное.',
  'worker_job_detail_cancelled_banner': 'Это задание было отменено.',
  'worker_job_detail_chat_with_client': 'Написать клиенту',
  'worker_job_detail_cancel_job_button': 'Отменить задание',
  'worker_job_detail_mark_completed_button': 'Отметить как выполненное',
  'worker_job_detail_taken_by_other_banner': 'Это задание уже назначено другому работнику.',
  'worker_job_detail_waiting_confirmation': "Вы подали заявку. Ожидайте подтверждения от клиента.",
  'worker_job_detail_apply_button': 'Подать заявку',
  'worker_job_detail_online_pill': 'В сети',
  'worker_job_detail_offline_pill': 'Не в сети',
  'worker_job_detail_photos_title': 'Фотографии',
  'worker_job_detail_photo_count_singular': '@count фото',
  'worker_job_detail_photo_count_plural': '@count фото',
  'job_history_card_payout_label': 'ВЫПЛАТА:',
  'worker_history_no_title': 'Без названия',
  'worker_history_location_not_specified': 'Местоположение не указано',
  'worker_history_na': 'Н/Д',
  'worker_history_status_posted': 'ОПУБЛИКОВАНО',
  'worker_history_status_applied': 'ЗАЯВКА ПОДАНА',
  'worker_my_jobs_title': 'Мои задания',
  'worker_my_jobs_empty': 'Задания не найдены',
  'worker_edit_profile_title': 'Редактировать профиль',
  'worker_edit_profile_take_photo': 'Сделать фото',
  'worker_edit_profile_choose_gallery': 'Выбрать из галереи',
  'worker_edit_profile_no_email': 'Не зарегистрировано с электронной почтой',
  'worker_edit_profile_change_photo': 'Изменить фото',
  'worker_edit_profile_hint_full_name': 'Полное имя',
  'worker_edit_profile_hint_email': 'Адрес электронной почты',
  'worker_edit_profile_hint_phone': 'Номер телефона',
  'worker_edit_profile_skills_label': 'НАВЫКИ',
  'worker_edit_profile_hint_add_skill': 'Добавить навык',
  'worker_edit_profile_cancel_button': 'Отмена',
  'worker_edit_profile_saving_button': 'Сохранение...',
  'worker_edit_profile_save_button': 'Сохранить изменения',
  'worker_favourites_title': 'Избранное',
  'worker_favourites_empty_title': 'Пока нет избранных заданий.',
  'worker_favourites_empty_subtitle': 'Нажмите на значок сердца на задании, чтобы сохранить его здесь.',
  'worker_help_tab_faqs': 'Частые вопросы',
  'worker_help_tab_submit_ticket': 'Отправить обращение',
  'worker_help_tab_live_chat': 'Онлайн-чат',
  'worker_help_appbar_title': 'Помощь и поддержка',
  'worker_help_live_badge': '24/7 НА СВЯЗИ',
  'worker_help_kb_section_title': 'БАЗА ЗНАНИЙ И ЧАСТЫЕ ВОПРОСЫ',
  'worker_help_no_results': 'Результаты не найдены',
  'worker_help_direct_assistance_title': 'ПРЯМАЯ ПОДДЕРЖКА',
  'worker_help_call_support_label': 'ПОЗВОНИТЬ В ПОДДЕРЖКУ',
  'worker_help_email_us_label': 'НАПИШИТЕ НАМ',
  'worker_help_search_hint': 'Поиск ответов, руководств...',
  'worker_help_label_category': 'Категория',
  'worker_help_label_subject': 'Тема',
  'worker_help_label_detailed_message': 'Подробное сообщение',
  'worker_help_select_category_hint': 'Выберите категорию',
  'worker_help_subject_hint': 'Краткое описание проблемы...',
  'worker_help_message_hint': 'Укажите все важные детали вашего обращения...',
  'worker_help_submit_ticket_button': 'Отправить обращение',
  'worker_help_support_ai_name': 'ИИ-поддержка Uybor',
  'worker_help_online_operator': 'ОПЕРАТОР НА СВЯЗИ',
  'worker_help_chat_input_hint': 'Введите ваш вопрос...',
  'faq_escrow_question': 'Как работает система эскроу-платежей?',
  'faq_escrow_answer': 'Когда вы нанимаете работника, ваш платеж надежно удерживается в эскроу и переводится ему только после того, как задание отмечено выполненным и одобрено вами.',
  'faq_category_payment': 'Оплата',
  'faq_fees_question': 'Есть ли комиссия за регистрацию?',
  'faq_fees_answer': 'Создание аккаунта и использование платформы полностью бесплатны. Небольшая комиссия взимается только при успешном завершении задания.',
  'faq_verification_question': 'Как работают значки верификации работников?',
  'faq_verification_answer': 'Работники получают значки верификации после предоставления действительных документов и прохождения проверки, что помогает вам нанимать с уверенностью.',
  'faq_category_verification': 'Верификация',
  'faq_dispute_question': 'Что делать, если возник спор?',
  'faq_dispute_answer': 'Откройте обращение в поддержку на вкладке «Отправить обращение» с деталями разногласия. Наша команда рассмотрит случай и поможет найти справедливое решение.',
  'faq_category_disputes': 'Споры',
  'faq_safety_question': 'Как защищены мои личные данные?',
  'faq_safety_answer': 'Все личные данные шифруются при передаче и хранении и никогда не передаются третьим лицам без вашего явного согласия.',
  'faq_category_safety': 'Безопасность',
  'faq_cancel_question': 'Могу ли я отменить задание после внесения гарантийного депозита?',
  'faq_cancel_answer': 'Да, вы можете отменить задание до того, как работник начнет его выполнение. В зависимости от сроков может взиматься частичная комиссия за отмену согласно нашим правилам.',
  'faq_cat_all': 'Все статьи',
  'faq_cat_payment': 'Оплата',
  'faq_cat_verification': 'Верификация',
  'faq_cat_disputes': 'Споры',
  'faq_cat_safety': 'Безопасность',
  'ticket_cat_payment': 'Оплата и эскроу',
  'ticket_cat_verification': 'Верификация',
  'ticket_cat_disputes': 'Споры',
  'ticket_cat_account': 'Аккаунт',
  'ticket_cat_tech': 'Техническая проблема',
  'ticket_cat_other': 'Другое',
  'chat_welcome_msg': 'Здравствуйте! Добро пожаловать в поддержку. Чем мы можем вам помочь сегодня?',
  'chat_time_just_now': 'Только что',
  'chat_time_now': 'Сейчас',
  'chat_auto_reply': 'Спасибо за обращение, один из наших специалистов скоро ответит.',
  'ticket_missing_title': 'Не хватает данных',
  'ticket_missing_msg': 'Пожалуйста, заполните тему и сообщение.',
  'ticket_submitted_title': 'Обращение отправлено',
  'ticket_submitted_msg': 'Наша команда поддержки скоро свяжется с вами.',
  'worker_profile_oops_title': 'Упс!',
  'worker_profile_name_empty_error': 'Имя не может быть пустым.',
  'worker_profile_saving_loader': 'Сохранение...',
  'worker_profile_update_failed_title': 'Обновление не удалось',
  'worker_profile_success_title': 'Успех',
  'worker_profile_updated_success_message': 'Профиль успешно обновлен!',
  'worker_profile_generic_error': 'Что-то пошло не так, пожалуйста, попробуйте еще раз.',
  'worker_profile_add_name_placeholder': 'Добавьте ваше имя',
  'worker_profile_not_provided': 'Не указано',
  'worker_profile_im_a_role': "Я — @role",
  'worker_lang_title': 'Выберите язык',
  'worker_lang_eng_sub': 'АНГЛИЙСКИЙ',
  'worker_lang_uzb_sub': 'УЗБЕКСКИЙ',
  'worker_lang_rus_sub': 'РУССКИЙ',
  'wallet_success_title': 'Успех',
  'wallet_deposit_success_message': 'Пополнение на @amount выполнено успешно',
  'wallet_insufficient_balance_title': 'Недостаточно средств',
  'wallet_insufficient_balance_message': "У вас недостаточно средств для вывода",
  'wallet_withdraw_success_message': 'Вывод средств успешно выполнен',
  'worker_profile_title': 'Профиль',
  'worker_profile_online': 'В СЕТИ',
  'worker_profile_offline': 'НЕ В СЕТИ',
  'worker_profile_personal_info': 'Личная информация',
  'worker_profile_wallet': 'Кошелек',
  'worker_profile_favourites': 'Избранное',
  'worker_profile_location': 'Местоположение',
  'worker_profile_location_sub': 'Активно для заданий поблизости',
  'worker_profile_settings': 'Настройки',
  'worker_profile_help_support': 'Помощь и поддержка',
  'worker_profile_logout': 'Выйти',
  'worker_profile_logout_title': 'Выйти',
  'worker_profile_logout_subtitle': 'Вы уверены, что хотите выйти?',
  'deposit_popup_title': 'Пополнить счет',
  'deposit_popup_select_card_type': 'ВЫБЕРИТЕ ТИП КАРТЫ',
  'deposit_popup_label_amount': 'СУММА (\$)',
  'deposit_popup_hint_amount': '\$ 50.00',
  'deposit_popup_label_card_number': 'НОМЕР КАРТЫ',
  'deposit_popup_hint_card_number': '8600 **** **** ****',
  'deposit_popup_top_text_card_number': 'UZCARD (8600)',
  'deposit_popup_label_expiry': 'СРОК ДЕЙСТВИЯ',
  'deposit_popup_hint_expiry': 'ММ/ГГ',
  'deposit_popup_label_cvv': 'CVV',
  'deposit_popup_hint_cvv': '***',
  'deposit_popup_label_cardholder_name': 'ИМЯ ВЛАДЕЛЬЦА КАРТЫ',
  'deposit_popup_hint_cardholder_name': 'ИВАН ИВАНОВ',
  'deposit_popup_confirm_button': 'Подтвердить пополнение',
  'worker_settings_title': 'Настройки',
  'worker_settings_language': 'Выберите язык',
  'worker_settings_notifications': 'Уведомления',
  'worker_settings_dark_mode': 'Темная тема',
  'worker_settings_dark_mode_sub': 'Переключение между светлой и темной темой',
  'worker_settings_become_client': 'Стать клиентом',
  'worker_settings_switch': 'Переключить',
  'worker_settings_app_version': 'Версия приложения',
  'worker_settings_version_val': '1.2.0 (Стабильная)',
  'worker_settings_acc_status': 'Статус аккаунта',
  'worker_settings_verified': 'Подтвержден',
  'worker_settings_security': 'Безопасность',
  'worker_settings_security_val': 'Защищено SSL/SMS',
  'withdraw_popup_title': 'Вывести средства',
  'withdraw_popup_method_card': 'Карта',
  'withdraw_popup_method_bank_account': 'Банковский счет',
  'withdraw_popup_label_amount': 'СУММА (\$)',
  'withdraw_popup_available_balance': 'ДОСТУПНО: @amount',
  'withdraw_popup_hint_amount': '\$ 100.00',
  'withdraw_popup_label_iban': 'БАНКОВСКИЙ СЧЕТ (IBAN)',
  'withdraw_popup_hint_iban': 'UZ99 4321 0000 1234 5678',
  'withdraw_popup_confirm_button': 'Подтвердить вывод',
  'worker_wallet_title': 'Кошелек',
  'worker_wallet_recent_transactions': 'Последние транзакции',
  'worker_wallet_see_all': 'Смотреть все',
  'worker_wallet_total_balance': 'Общий баланс',
  'worker_wallet_deposit_button': '+ Пополнить',
  'worker_wallet_withdraw_button': '- Вывести',
  'worker_wallet_tx_plumbing_title': 'Оплата за сантехнику',
  'worker_wallet_tx_bank_withdrawal_title': 'Вывод на банковский счет',
  'worker_wallet_tx_hvac_title': 'Оплата за отопление и вентиляцию',
  'worker_wallet_tx_time_today': 'Сегодня, 14:30',
  'worker_wallet_tx_time_yesterday': 'Вчера, 16:15',
  'worker_wallet_tx_time_mar5': '5 марта, 11:20',
  'worker_personal_info_title': 'Личная информация',
  'worker_personal_info_full_name_label': 'ПОЛНОЕ ИМЯ',
  'worker_personal_info_email_label': 'АДРЕС ЭЛЕКТРОННОЙ ПОЧТЫ',
  'worker_personal_info_phone_label': 'НОМЕР ТЕЛЕФОНА',
  'worker_personal_info_skills_label': 'НАВЫКИ',
  'worker_personal_info_no_skills': 'Пока нет добавленных навыков',
  'worker_personal_info_edit_button': 'Редактировать профиль',
  'worker_bottom_nav_home': 'Главная',
  'worker_bottom_nav_chat': 'Чат',
  'worker_bottom_nav_my_jobs': 'Мои задания',
  'worker_bottom_nav_profile': 'Профиль',
  'client_bottom_nav_home': 'Главная',
  'client_bottom_nav_chat': 'Чат',
  'client_bottom_nav_my_jobs': 'Мои задания',
  'client_bottom_nav_profile': 'Профиль',
  'role_selection_title_line1': 'Кто ты',
  'role_selection_title_line2': 'такой?',
  'role_selection_post_job': 'Разместить заказ',
  'role_selection_find_work': 'Найти работу',
  'role_selection_continue': 'Продолжить',
  'role_selection_error_title': 'Ошибка',
  'role_selection_error_message': 'Пожалуйста, выберите роль для продолжения',
  'languagesheettitle':'Выберите язык',
  'languagesheetsubtitle':'Вы можете изменить это в любой момент в настройках.',
  'languagesheetloading':'Пожалуйста, подождите...',
  'languagesheetcontinue':'Продолжать',
  "edit_profile_section_personal": "Личная информация",
  "edit_profile_email_locked_note": "Электронную почту нельзя изменить",
  "edit_profile_btn_saving": "Сохранение...",
  "worker_edit_profile_section_personal": "Личная информация",
  "worker_edit_profile_email_locked_note": "Электронную почту нельзя изменить",
  "worker_edit_profile_no_skills_yet": "Навыки еще не добавлены",
  "worker_personal_info_section_contact": "Контактная информация",
  "personal_info_section_contact": "Контактная информация",
  "workersettingsnack":"Перешел на",
  "post_job_image_pick_error_title": "Ошибка",
  "post_job_image_pick_error_message": "При выборе фотографии произошла ошибка. Пожалуйста, попробуйте еще раз.",
  'wallet_error_title': 'Ошибка',
  'wallet_error_not_logged_in': 'Пожалуйста, сначала войдите в систему.',
  'wallet_error_invalid_amount': 'Пожалуйста, введите корректную сумму.',
  'wallet_error_something_went_wrong': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  'wallet_topup_success': 'Пополнение успешно выполнено',
  'wallet_topup_failed': 'Не удалось пополнить счет',
  'deposit_popup_processing': 'Обработка...',
  'post_job_estimating_fee': 'Расчет комиссии платформы...',
  'post_job_platform_fee_label': 'Комиссия платформы',
  'post_job_total_to_pay_label': 'Итого к оплате',
};