Map<String, String> uzUZ = {
  'common_continue': 'Davom etish',
  'onboarding_language_title': 'Ishga xush kelibsiz',
  'onboarding_language_subtitle':
  'Ish va xodimlarni topish usulini tubdan o‘zgartirish.',
  'auth_signup_login_title': 'Ro‘yxatdan o‘ting yoki kiring',
  'auth_create_account': 'Hisob yaratish',
  'auth_details_subtitle': 'Hisobingizga kirish uchun maʼlumotlaringizni kiriting',
  'auth_phone_tab': 'Telefon',
  'auth_email_tab': 'Elektron pochta',
  'auth_phone_hint': '+1 (555) 000-0000',
  "auth_button_continue" : "Davom etish",
  "auth_button_loading" : 'Пожалуйста, подождите...',
  'auth_email_hint': 'Elektron pochta manzilini kiriting',
  'auth_error_enter_phone': 'Iltimos, telefon raqamingizni kiriting.',
  'auth_error_valid_phone': 'Yaroqli telefon raqamini kiriting (10–15 ta raqam)',
  'auth_error_enter_email': 'Iltimos, elektron pochta manzilingizni kiriting.',
  'auth_error_valid_email': 'Yaroqli elektron pochta manzilini kiriting',
  'auth_error_general': 'Xato',
  'auth_error_something_wrong': 'Nimadir noto‘g‘ri ketdi',
  'auth_error_invalid_response': 'Serverdan noto‘g‘ri javob',
  'auth_error_retry': 'Nimadir noto‘g‘ri ketdi. Iltimos, qayta urinib ko‘ring.',
  'auth_loader_wait': 'Iltimos kuting...',
  'api_error_invalid_response': 'Serverdan noto‘g‘ri javob',
  'api_error_something_wrong': 'Nimadir noto‘g‘ri ketdi',
  'api_error_no_connection': 'Internetga ulanish yo‘q yoki serverga ulanib bo‘lmayapti',
  'chat_error_load_list': 'Suhbatlar ro‘yxatini yuklab bo‘lmadi',
  'chat_error_load_messages': 'Xabarlarni yuklab bo‘lmadi',
  'chat_error_send_message': 'Xabar yuborib bo‘lmadi',
  'chat_error_no_response': 'Serverdan javob olinmadi',
  'chat_error_unexpected_response': 'Kutilmagan server javobi',
  'chat_error_request_failed': 'So‘rov bajarilmadi',
  'chat_ok': 'KELISHDIKMI',
  'profile_error_session_not_found': 'Foydalanuvchi sessiyasi topilmadi. Iltimos, qayta tizimga kiring.',
  'job_error_not_logged_in': "Siz tizimga kirmagansiz. Iltimos, qayta kiring va urinib ko‘ring.",
  'job_success_posted': 'Ish e"loni muvaffaqiyatli joylashtirildi!',
  'job_error_failed_post': 'Ish e"lonini joylashtirib bo‘lmadi. Iltimos, qayta urinib ko‘ring.',
  'job_error_something_went_wrong': 'Nimadir noto‘g‘ri ketdi. Iltimos, aloqani tekshirib, qayta urinib ko‘ring.',
  'job_cancelled_success': 'Ish bekor qilindi.',
  'job_cancelled_unable': 'Ishni bekor qilib bo‘lmadi.',
  'job_confirmed_success': 'Ish muvaffaqiyatli tasdiqlandi.',
  'job_confirmed_unable': 'Ishni tasdiqlab bo‘lmadi.',
  'job_select_worker_success': 'Ishchi muvaffaqiyatli tanlandi.',
  'job_select_worker_unable': 'Ishchini tanlab bo‘lmadi.',
  'notif_error_not_logged_in': 'Foydalanuvchi tizimga kirmagan',
  'notif_error_server': 'Server xatosi',
  'notif_error_something_went_wrong': 'Nimadir noto‘g‘ri ketdi. Iltimos, qayta urinib ko‘ring.',
  'status_error_title': 'Xato',
  'status_error_update_failed': 'Holatni yangilab bo‘lmadi. Iltimos, qayta urinib ko‘ring.',
  'status_loader_going_online': 'Onlaynga chiqilmoqda...',
  'status_loader_going_offline': 'Oflaynga o‘tilmoqda...',
  'status_snackbar_failed_title': 'Yangilash muvaffaqiyatsiz',
  'online_status_empty_response': 'Serverdan bo‘sh javob keldi.',
  'online_status_success_msg': 'Holat muvaffaqiyatli yangilandi!',
  'online_status_failed_msg': 'Holatni yangilab bo‘lmadi.',
  'online_status_error_connection': 'Nimadir noto‘g‘ri ketdi. Iltimos, internet aloqangizni tekshiring.',
  'worker_job_applied_success': 'Muvaffaqiyatli ariza berildi!',
  'worker_job_complete_success': 'Ish bajarilgan deb belgilandi.',
  'worker_job_complete_unable': 'Ishni yakunlab bo‘lmadi.',
  'worker_job_confirm_success': 'Muvaffaqiyatli tasdiqlandi.',
  'worker_job_confirm_unable': 'Tasdiqlab bo‘lmadi.',
  'worker_job_error_something_went_wrong': 'Nimadir noto‘g‘ri ketdi. Iltimos, aloqangizni tekshirib, qayta urinib ko‘ring.',
  'dialog_logout_title': 'Chiqish',
  'dialog_logout_subtitle': 'Tizimdan chiqishni xohlaysizmi?',
  'dialog_delete_title': 'O‘chirish',
  'dialog_delete_subtitle': 'Bu amalni bekor qilib bo‘lmaydi',
  'dialog_default_logout_title': 'Chiqish',
  'dialog_default_logout_subtitle': 'Tizimdan chiqishni xohlaysizmi?',
  'dialog_default_confirm_text': 'Chiqish',
  'dialog_default_cancel_text': 'Bekor qilish',
  'error_default_title': 'Xato',
  'success_default_title': 'Muvaffaqiyat',
  'info_default_title': 'Maʼlumot',
  'image_picker_title': 'Profil rasmini tanlang',
  'image_picker_camera': 'Kamera',
  'image_picker_gallery': 'Galereya',
  'custom_text_field_search_hint': 'Qidirish...',
  'otp_error_complete_code': 'Iltimos, 6 xonali kodni to‘liq kiriting',
  'otp_verifying': 'Tekshirilmoqda...',
  'otp_default_invalid': 'Noto‘g‘ri tasdiqlash kodi',
  'otp_error_invalid_response': 'Serverdan noto‘g‘ri javob',
  'otp_error_account_blocked_title': 'Hisob bloklangan',
  'otp_error_account_blocked_subtitle': 'Hisobingiz bloklangan. Iltimos, qo‘llab-quvvatlash xizmati bilan bog‘laning.',
  'otp_resend_success_title': 'Yuborildi',
  'otp_resend_success_msg': 'Yangi tasdiqlash kodi yuborildi.',
  'otp_resend_error_msg': 'Kodni qayta yuborib bo‘lmadi',
  'otp_error_something_went_wrong': 'Nimadir noto‘g‘ri ketdi. Iltimos, qayta urinib ko‘ring.',
  'otp_error_default': 'Xato',
  'otp_screen_title': 'Kodni tasdiqlash',
  'otp_screen_subtitle': 'Quyidagi manzilga yuborilgan 6 xonali kodni kiriting:\n@contact',
  'otp_screen_resending': 'Qayta yuborilmoqda...',
  'otp_screen_resend_prompt': "Kodni olmadingizmi? Qayta yuborish",
  'otp_screen_button_verifying': 'Tekshirilmoqda...',
  'otp_screen_button_verify': 'Tasdiqlash',
  'job_card_flexible': 'MOSLASHUVCHAN',
  'job_card_attributes': 'XUSUSIYATLAR',
  'job_card_posted_prefix': 'Joylashtirilgan ',
  'job_card_see_detail': 'Batafsil ma"lumotni ko"rish',
  'client_confirm_worker_selecting': 'Ishchi tanlanmoqda...',
  'client_confirm_worker_selected_title': 'Ishchi tanlandi',
  'client_confirm_worker_action_failed_title': 'Amal bajarilmadi',
  'client_confirm_worker_cancelling': 'Ish bekor qilinmoqda...',
  'client_confirm_worker_cancelled_title': 'Ish bekor qilindi',
  'client_confirm_worker_completing': 'Ish bajarilgan deb belgilanmoqda...',
  'client_confirm_worker_completed_title': 'Ish bajarildi',
  'client_confirm_worker_header_title': 'Ishchi profili',
  'client_confirm_worker_skills': 'Ko‘nikmalar',
  'client_confirm_worker_job_budget': 'Ish byudjeti',
  'client_confirm_worker_payment_via': '@mode orqali to‘lov',
  'client_confirm_worker_completed_banner': 'Bu ish bajarilgan deb belgilandi.',
  'client_confirm_worker_cancelled_banner': 'Bu ish bekor qilindi.',
  'client_confirm_worker_chat_button': 'Ishchi bilan suhbat',
  'client_confirm_worker_unavailable': 'Mavjud emas',
  'client_confirm_worker_cancel_job': 'Ishni bekor qilish',
  'client_confirm_worker_accept_worker': 'Ishchini qabul qilish',
  'client_confirm_worker_mark_completed': 'Bajarildi deb belgilash',
  'client_confirm_worker_active_strike': '@count faol ogohlantirish',
  'client_confirm_worker_active_strikes': '@count faol ogohlantirish',
  'client_confirm_worker_applied_for': 'Ariza berilgan',
  'client_jobs_error_loading': 'Ishlaringizni yuklab bo‘lmadi. Qayta urinish uchun pastga torting.',
  'client_jobs_tab_all': 'Barchasi',
  'client_home_welcome': 'Xush kelibsiz',
  'client_home_discover_jobs': 'Ishlarni kashf eting',
  'client_home_subtitle': 'Barcha joylashtirilgan vazifalaringiz bir joyda',
  'client_home_no_jobs': 'Bu kategoriyada hozircha ishlar mavjud emas.',
  'client_home_your_posted_jobs': 'Sizning joylashtirgan ishlaringiz',
  'client_home_online': 'ONLAYN',
  'client_home_offline': 'OFLAYN',
  'client_home_wallet': 'HAMYON',
  'client_home_active_jobs': 'FAOL ISHLAR',
  'client_home_retry': 'Qayta urinish',
  'model_worker_unknown': 'Noma’lum ishchi',
  'model_worker_rating_new': 'Yangi',
  'model_job_general': 'Umumiy',
  'model_job_untitled': 'Nomsiz vazifa',
  'model_job_urgency_urgent': 'Shoshilinch',
  'model_job_urgency_critical': 'Muhim',
  'model_job_urgency_flexible': 'Moslashuvchan',
  'model_job_urgency_normal': 'Oddiy',
  'model_job_priority': 'USTUVORLIK',
  'model_job_budget_hourly': 'Soatlik narx',
  'model_job_budget_negotiable': 'Kelishiladigan',
  'model_job_budget_fixed': 'Belgilangan narx',
  'model_job_budget_hourly_suffix': '/soat',
  'model_job_budget_hourly_label': 'Soatlik',
  'model_job_budget_to_be_discussed': 'Chatda muhokama qilinadi',
  'model_job_budget_one_time': ' (bir martalik)',
  'model_job_payment_card': 'Karta',
  'model_job_payment_cash': 'Naqd',
  'model_job_payment_wallet': 'Hamyon',
  'model_job_payment_escrow': 'Eskrou',
  'model_job_payment_commission': 'Faqat komissiya',
  'model_job_payment_not_specified': 'Ko‘rsatilmagan',
  'model_job_datetype_custom': 'Boshqa sana',
  'model_job_datetype_today': 'Bugun',
  'job_detail_loading_applicants': 'Nomzodlar yuklanmoqda...',
  'job_detail_refreshing': 'Yangilanmoqda...',
  'job_detail_not_found': 'Ish topilmadi',
  'job_detail_overview': 'Umumiy ma’lumot',
  'job_detail_category': 'Kategoriya',
  'job_detail_subcategory': 'Kichik kategoriya',
  'job_detail_city': 'Shahar',
  'job_detail_location': 'Manzil',
  'job_detail_status': 'Holat',
  'job_detail_budget_payment': 'Byudjet va to‘lov',
  'job_detail_budget_type': 'Byudjet turi',
  'job_detail_amount': 'Summa',
  'job_detail_payment_mode': 'To‘lov usuli',
  'job_detail_schedule': 'Jadval',
  'job_detail_date': 'Sana',
  'job_detail_start_time': 'Boshlanish vaqti',
  'job_detail_end_time': 'Tugash vaqti',
  'job_detail_date_type': 'Sana turi',
  'job_detail_description': 'Tavsif',
  'job_detail_no_description': 'Tavsif kiritilmagan.',
  'job_detail_attributes': 'Xususiyatlar',
  'job_detail_interested_worker': 'Qiziqqan ishchi',
  'job_detail_no_applicants_yet': 'Hozircha hech kim ariza bermagan',
  'job_detail_worker_applied': 'Bu ishga @count ta ishchi ariza berdi',
  'job_detail_assigned_banner': 'Bu ishga allaqachon ishchi tayinlangan.',
  'job_detail_photos': 'Rasmlar',
  'job_detail_photo_count_single': '@count ta rasm',
  'job_detail_photo_count_plural': '@count ta rasm',
  'job_detail_see_detail': 'Batafsil',
  'job_detail_online': 'Onlayn',
  'job_detail_offline': 'Oflayn',
  'job_detail_strike_single': '@count ogohlantirish',
  'job_detail_strike_plural': '@count ogohlantirish',
  'job_detail_no_workers_applied': 'Hozircha hech qanday ishchi ariza bermagan',
  'client_my_job_tab_active': 'Faol',
  'client_my_job_tab_completed': 'Bajarilgan',
  'client_my_job_tab_cancelled': 'Bekor qilingan',
  'client_my_jobs_title': 'Mening ishlarim',
  'client_my_jobs_empty_prefix': '',
  'client_my_jobs_empty_suffix': ' ishlar topilmadi',
  'client_my_jobs_location_fallback': 'Masofaviy manzil',
  'client_my_jobs_date_fallback': 'Mavjud emas',
  'client_my_jobs_title_fallback': 'Nomsiz',
  'client_my_jobs_desc_fallback': 'Tavsif mavjud emas.',
  'client_my_jobs_budget_fixed': 'Belgilangan',
  'edit_profile_title': 'Profilni tahrirlash',
  'edit_profile_change_photo': 'Rasmni o‘zgartirish',
  'edit_profile_hint_name': 'To‘liq ism',
  'edit_profile_hint_email': 'Elektron pochta manzili',
  'edit_profile_email_fallback': 'Elektron pochta bilan ro‘yxatdan o‘tilmagan',
  'edit_profile_hint_phone': 'Telefon raqami',
  'edit_profile_btn_cancel': 'Bekor qilish',
  'edit_profile_btn_save': 'O‘zgarishlarni saqlash',
  'favourites_title_my': 'Mening ',
  'favourites_title_highlight': 'Sevimlilarim',
  'favourites_saved_jobs_count': '@count ta saqlangan ish',
  'favourites_empty_title': 'Hozircha sevimlilar yo‘q',
  'favourites_empty_subtitle': 'Keyinroq saqlash uchun istalgan ishdagi\nxatcho‘p belgisini bosing.',
  'help_support_tab_faqs': 'Savol-javoblar',
  'help_support_tab_submit_ticket': 'Murojaat yuborish',
  'help_support_tab_live_chat': 'Jonli chat',
  'help_support_title': 'Yordam va qo‘llab-quvvatlash',
  'help_support_live_badge': '24/7 FAOL',
  'help_support_kb_section_title': 'BILIMLAR BAZASI VA SAVOL-JAVOBLAR',
  'help_support_no_results': 'Natijalar topilmadi',
  'help_support_direct_assistance_title': 'TO‘G‘RIDAN-TO‘G‘RI YORDAM',
  'help_support_call_label': 'QO‘LLAB-QUVVATLASHGA QO‘NG‘IROQ',
  'help_support_email_label': 'BIZGA YOZING',
  'help_support_search_hint': 'Javoblar, qo‘llanmalarni qidirish...',
  'help_support_category_label': 'Kategoriya',
  'help_support_select_category_hint': 'Kategoriyani tanlang',
  'help_support_subject_label': 'Mavzu',
  'help_support_subject_hint': 'Muammoning qisqacha tavsifi...',
  'help_support_message_label': 'Batafsil xabar',
  'help_support_message_hint': 'So‘rovingizga oid barcha tegishli tafsilotlarni kiriting...',
  'help_support_submit_ticket_button': 'Murojaat yuborish',
  'help_support_ai_name': 'Uybor AI yordamchisi',
  'help_support_online_operator': 'ONLAYN OPERATOR',
  'help_support_chat_input_hint': 'Savolingizni yozing...',
  'faq_question_escrow': 'To‘lovlarni eskrou orqali saqlash tizimi qanday ishlaydi?',
  'faq_answer_escrow': 'Ishchi yollaganingizda, to‘lovingiz xavfsiz tarzda eskrouda saqlanadi va faqat ish bajarilgan deb belgilanib, siz tomondan tasdiqlanganidan so‘ng unga o‘tkaziladi.',
  'faq_category_payment': 'To‘lov',
  'faq_question_fees': 'Ro‘yxatdan o‘tish uchun xizmat haqi bormi?',
  'faq_answer_fees': 'Hisob yaratish va platformadan foydalanish butunlay bepul. Kichik xizmat haqi faqat ish muvaffaqiyatli yakunlanganda olinadi.',
  'faq_question_badges': 'Ishchilarni tasdiqlash nishonlari qanday ishlaydi?',
  'faq_answer_badges': 'Ishchilar amaldagi shaxsni tasdiqlovchi hujjatlarni taqdim etib, tekshiruv jarayonidan o‘tgach tasdiqlash nishonlarini oladi, bu esa sizga ishonch bilan ishga olishga yordam beradi.',
  'faq_category_verification': 'Tasdiqlash',
  'faq_question_dispute': 'Nizo yuzaga kelsa, nima qilishim kerak?',
  'faq_answer_dispute': '«Murojaat yuborish» bo‘limidan kelishmovchilik tafsilotlari bilan murojaat oching. Jamoamiz vaziyatni ko‘rib chiqib, adolatli yechim topishga yordam beradi.',
  'faq_category_disputes': 'Nizolar',
  'faq_question_data': 'Shaxsiy ma’lumotlarim qanday himoyalanadi?',
  'faq_answer_data': 'Barcha shaxsiy ma’lumotlar uzatishda va saqlashda shifrlanadi hamda sizning aniq roziligingizsiz uchinchi tomonlarga hech qachon berilmaydi.',
  'faq_category_safety': 'Xavfsizlik',
  'faq_question_cancel': 'Xavfsiz depozit qilinganidan keyin ishni bekor qila olamanmi?',
  'faq_answer_cancel': 'Ha, ishchi ishni boshlashidan oldin bekor qilishingiz mumkin. Vaqtga qarab, qoidalarimizga muvofiq qisman bekor qilish haqi olinishi mumkin.',
  'faq_cat_all_articles': 'Barcha maqolalar',
  'ticket_cat_payment_escrow': 'To‘lov va eskrou',
  'ticket_cat_verification': 'Tasdiqlash',
  'ticket_cat_disputes': 'Nizolar',
  'ticket_cat_account': 'Hisob',
  'ticket_cat_technical': 'Texnik muammo',
  'ticket_cat_other': 'Boshqa',
  'support_chat_welcome': 'Salom! Qo‘llab-quvvatlash xizmatiga xush kelibsiz. Sizga qanday yordam bera olamiz?',
  'support_chat_time_just_now': 'Hozirgina',
  'support_chat_time_now': 'Hozir',
  'support_chat_auto_reply': 'Murojaat qilganingiz uchun rahmat, mutaxassislarimizdan biri tez orada javob beradi.',
  'support_snackbar_missing_title': 'Maʼlumotlar yetishmayapti',
  'support_snackbar_missing_msg': 'Iltimos, mavzu va xabarni to‘ldiring.',
  'support_snackbar_success_title': 'Murojaat yuborildi',
  'support_snackbar_success_msg': 'Qo‘llab-quvvatlash jamoamiz tez orada siz bilan bog‘lanadi.',
  'profile_fetch_error_title': 'Xato',
  'profile_update_missing_name': 'Ism bo‘sh bo‘lishi mumkin emas.',
  'profile_update_missing_name_title': 'Voy!',
  'profile_update_loader': 'Saqlanmoqda...',
  'profile_update_failed_title': 'Yangilash muvaffaqiyatsiz',
  'profile_update_fallback_error': 'Nimadir noto‘g‘ri ketdi, iltimos qayta urinib ko‘ring.',
  'profile_update_success_title': 'Muvaffaqiyat',
  'profile_update_success_msg': 'Profil muvaffaqiyatli yangilandi!',
  'profile_skill_empty_title': 'Voy!',
  'profile_skill_empty_msg': 'Ko‘nikma nomi bo‘sh bo‘lishi mumkin emas.',
  'profile_skill_exists_title': 'Allaqachon qo‘shilgan',
  'profile_skill_exists_msg': 'Bu ko‘nikma allaqachon ro‘yxatingizda mavjud.',
  'profile_fallback_name': 'Ismingizni kiriting',
  'profile_fallback_email': 'Kiritilmagan',
  'profile_fallback_phone': 'Kiritilmagan',
  'profile_role_client': 'Mijoz',
  'profile_role_worker': 'Ishchi',
  'profile_role_prefix': "Men @role man",
  'client_profile_title': 'Profil',
  'client_profile_online': 'ONLAYN',
  'client_profile_offline': 'OFLAYN',
  'client_profile_personal_info': 'Shaxsiy maʼlumot',
  'client_profile_wallet': 'Hamyon',
  'client_profile_favourites': 'Sevimlilar',
  'client_profile_location': 'Manzil',
  'client_profile_location_subtitle': 'Yaqin atrofdagi ishlar uchun faol',
  'client_profile_settings': 'Sozlamalar',
  'client_profile_help_support': 'Yordam va qo‘llab-quvvatlash',
  'client_profile_logout': 'Chiqish',
  'client_profile_logout_confirm': 'Tizimdan chiqishni xohlaysizmi?',
  'settings_title': 'Sozlamalar',
  'settings_lang_title': 'Tilni tanlang',
  'settings_notifications_title': 'Bildirishnomalar',
  'settings_dark_mode_title': 'Tungi rejim',
  'settings_dark_mode_subtitle': 'Yorug‘ va qorong‘i rejim o‘rtasida almashtirish',
  'settings_become_worker_title': 'Ishchi bo‘lish',
  'settings_switch_btn': 'Almashtirish',
  'settings_info_version_key': 'Ilova versiyasi',
  'settings_info_version_val': '1.2.0 (Barqaror)',
  'settings_info_status_key': 'Hisob holati',
  'settings_info_status_val': 'Tasdiqlangan',
  'settings_info_security_key': 'Xavfsizlik',
  'settings_info_security_val': 'SSL/SMS bilan himoyalangan',
  'settings_logout_loader': 'Tizimdan chiqilmoqda...',
  'settings_logout_error_title': 'Xato',
  'settings_logout_error_msg': 'Tizimdan chiqib bo‘lmadi. Iltimos, qayta urinib ko‘ring.',
  'settings_ctrl_err_session_title': 'Xato',
  'settings_ctrl_err_session_msg': 'Foydalanuvchi sessiyasi topilmadi.',
  'settings_ctrl_loader_switching': 'Rejim almashtirilmoqda...',
  'settings_ctrl_success_title': 'Muvaffaqiyat',
  'settings_ctrl_success_msg': 'Rejim muvaffaqiyatli almashtirildi',
  'settings_ctrl_err_switch': 'Rolni almashtirib bo‘lmadi',
  'settings_ctrl_err_general': 'Nimadir noto‘g‘ri ketdi. Iltimos, qayta urinib ko‘ring.',
  'settings_ctrl_loader_logout': 'Tizimdan chiqilmoqda...',
  'settings_ctrl_err_logout': 'Tizimdan chiqib bo‘lmadi. Iltimos, qayta urinib ko‘ring.',
  'wallet_title': 'Hamyon',
  'wallet_balance_title': 'Umumiy balans',
  'wallet_recent_tx': 'So‘nggi tranzaksiyalar',
  'wallet_see_all': 'Barchasini ko‘rish',
  'wallet_btn_deposit': '+ Depozit',
  'wallet_btn_withdraw': '- Yechish',
  'wallet_tx_plumbing': 'Santexnika uchun to‘lov',
  'wallet_tx_withdrawal': 'Bankka o‘tkazma',
  'wallet_tx_hvac': 'Isitish/shamollatish uchun to‘lov',
  'wallet_tx_time_today': 'Bugun, 14:30',
  'wallet_tx_time_yesterday': 'Kecha, 16:15',
  'wallet_tx_time_old': '5-mart, 11:20',
  'wallet_ctrl_success_title': 'Muvaffaqiyat',
  'wallet_ctrl_deposit_msg': '\$%s miqdoridagi depozit muvaffaqiyatli amalga oshirildi',
  'wallet_ctrl_err_balance_title': 'Balans yetarli emas',
  'wallet_ctrl_err_balance_msg': 'Yechish uchun mablag‘ingiz yetarli emas',
  'wallet_ctrl_withdraw_msg': 'Mablag‘ muvaffaqiyatli yechildi',
  'deposit_title': 'Mablag‘ kiritish',
  'deposit_select_card': 'KARTA TURINI TANLANG',
  'deposit_label_amount': 'SUMMA (\$)',
  'deposit_hint_amount': '\$ 50.00',
  'deposit_label_card_num': 'KARTA RAQAMI',
  'deposit_hint_card_num': '8600 **** **** ****',
  'deposit_top_uzcard': 'UZCARD (8600)',
  'deposit_label_expiry': 'AMAL QILISH MUDDATI',
  'deposit_hint_expiry': 'OO/YY',
  'deposit_label_cvv': 'CVV',
  'deposit_hint_cvv': '***',
  'deposit_label_name': 'KARTA EGASINING ISMI',
  'deposit_hint_name': 'AZIZ AZIZOV',
  'deposit_btn_confirm': 'Depozitni tasdiqlash',
  'withdraw_title': 'Mablag‘ yechish',
  'withdraw_amount_label': 'SUMMA (\$)',
  'withdraw_available_prefix': 'MAVJUD: \$',
  'withdraw_hint_amount': '\$ 100.00',
  'withdraw_bank_label': 'BANK HISOBI (IBAN)',
  'withdraw_hint_iban': 'UZ99 4321 0000 1234 5678',
  'withdraw_btn_confirm': 'Yechishni tasdiqlash',
  'post_job_title_post_a': 'Vazifa ',
  'post_job_title_task': 'joylash',
  'post_job_subtitle': 'Ishingiz uchun mos mutaxassisni toping',
  'post_job_task_title_label': 'Vazifa nomi',
  'post_job_task_title_hint': 'masalan, divanni ko‘chirishga yordam',
  'post_job_category_label': 'Kategoriya',
  'post_job_select_category_default': 'Kategoriyani\ntanlang',
  'post_job_subcategory_label': 'Kichik kategoriya',
  'post_job_select_subcategory_default': 'Kichik kategoriyani\ntanlang',
  'post_job_select_category_sheet_title': 'Kategoriyani tanlang',
  'post_job_select_subcategory_sheet_title': 'Kichik kategoriyani tanlang',
  'post_job_all_subcategories': 'Barcha kichik kategoriyalar',
  'post_job_location_label': 'Manzil va joylashuv',
  'post_job_location_hint': 'masalan, Park ko‘chasi 45, Toshkent',
  'post_job_description_label': 'Tavsif',
  'post_job_description_hint': 'Ish talablari va ko‘lamini tavsiflang...',
  'post_job_budget_title': 'Byudjet',
  'post_job_budget_subtitle_fixed': 'Bir martalik umumiy to‘lov',
  'post_job_budget_subtitle_hourly': 'Ishlangan soatlar uchun to‘lov',
  'post_job_budget_subtitle_negotiable': 'Narx ishchi bilan bevosita muhokama qilinadi va kelishiladi',
  'post_job_tab_fixed_price': 'Belgilangan\nnarx',
  'post_job_tab_hourly_rate': 'Soatlik\nnarx',
  'post_job_tab_negotiable': 'Kelishiladigan',
  'post_job_amount_label': 'Summa',
  'post_job_currency_uzs': 'UZS',
  'post_job_amount_hint': '100',
  'post_job_payment_type_label': 'To‘lov turi',
  'post_job_rate_per_hour_label': 'Soatlik narx',
  'post_job_rate_hint': '25',
  'post_job_estimated_hours_label': 'Taxminiy soatlar',
  'post_job_optional': '(Majburiy emas)',
  'post_job_hours_hint': '4',
  'post_job_negotiable_budget_title': 'Kelishiladigan byudjet',
  'post_job_negotiable_budget_desc': 'Byudjet chatda ishchi bilan muhokama qilinadi va kelishiladi.',
  'post_job_payment_cash': 'Naqd',
  'post_job_payment_card': 'Karta',
  'post_job_payment_wallet': 'Hamyon',
  'post_job_schedule_badge': 'Jadval',
  'post_job_select_start_time_title': 'Boshlanish vaqtini tanlang',
  'post_job_select_start_time_message': 'Iltimos, avval boshlanish vaqtini tanlang',
  'post_job_start_time_label': 'Boshlanish vaqti',
  'post_job_end_time_label': 'Tugash vaqti',
  'post_job_choose_date_label': 'Sanani tanlang',
  'post_job_today': 'Bugun',
  'post_job_custom_date': 'Boshqa sana...',
  'post_job_urgency_label': 'Shoshilinchlik',
  'post_job_urgent': 'Shoshilinch',
  'post_job_flexible': 'Moslashuvchan',
  'post_job_photo_attachment_label': 'Rasm biriktirish',
  'post_job_drag_drop_photos': 'Rasmlarni tortib tashlang yoki tanlash uchun bosing',
  'post_job_photos_limit_hint': '3 tagacha rasm, JPG yoki PNG',
  'post_job_cancel_button': 'Bekor qilish',
  'post_job_submit_button': 'Yuborish',
  'personal_info_title': 'Shaxsiy maʼlumot',
  'personal_info_label_name': 'TO‘LIQ ISM',
  'personal_info_label_email': 'ELEKTRON POCHTA MANZILI',
  'personal_info_label_phone': 'TELEFON RAQAMI',
  'personal_info_btn_edit': 'Profilni tahrirlash',
  // Delivery & Logistics
  'category_delivery': 'Yetkazib berish va logistika',
  'category_sub_small_item': 'Kichik buyum va posilka yetkazib berish',
  'category_sub_grocery': 'Oziq-ovqat yetkazib berish',
  'category_sub_heavy_freight': 'Og‘ir yuk va kargo tashish',
  'category_sub_document': 'Hujjat va yuridik kuryerlik',

  // Handyman & Repairs
  'category_handyman': 'Usta xizmatlari va ta’mirlash',
  'category_sub_plumbing': 'Santexnika ta’miri',
  'category_sub_electrical': 'Elektr ta’miri',
  'category_sub_furniture': 'Mebel yig‘ish',
  'category_sub_carpentry': 'Duradgorlik va yog‘ochsozlik',
  'category_sub_painting': 'Bo‘yash va gipsokarton ishlari',
  'category_sub_appliance': 'Maishiy texnikani o‘rnatish va ta’mirlash',

  // Cleaning Services
  'category_cleaning': 'Tozalash xizmatlari',
  'category_sub_house_clean': 'Uy va kvartira tozalash',
  'category_sub_deep_clean': 'Chuqur va ko‘chib ketishdan oldingi tozalash',
  'category_sub_laundry': 'Kir yuvish va dazmollash',
  'category_sub_window_clean': 'Deraza va oyna tozalash',
  'category_sub_carpet_clean': 'Gilam va mebel tozalash',

  // Moving & Storage
  'category_moving': 'Ko‘chirish va saqlash',
  'category_sub_local_move': 'Mahalliy ko‘chirish',
  'category_sub_packing': 'Yuk qadoqlash va ochish yordami',
  'category_sub_heavy_lifting': 'Og‘ir yuk ko‘tarish va yuklash',
  'category_sub_office_move': 'Ofis va tijorat ko‘chirilishi',

  // Pet Care
  'category_pet_care': 'Uy hayvonlariga g‘amxo‘rlik',
  'category_sub_pet_sitting': 'Uy hayvonlarini boqish va saqlash',
  'category_sub_dog_walking': 'It sayr qildirish',
  'category_sub_pet_grooming': 'Uy hayvonlarini parvarish qilish va yuvish',
  'category_sub_pet_training': 'Uy hayvonlarini dressirovka qilish',

  // Tech & IT Support
  'category_tech_it': 'Texnika va IT yordami',
  'category_sub_computer_repair': 'Kompyuter va noutbuk ta’miri',
  'category_sub_smart_home': 'Aqlli uy va Wi-Fi sozlash',
  'category_sub_phone_repair': 'Telefon va planshet ta’miri',
  'category_sub_tv_mounting': 'Televizor o‘rnatish va audio sozlash',

  // Beauty & Wellness
  'category_beauty_wellness': 'Go‘zallik va sog‘lomlashtirish',
  'category_sub_haircut_styling': 'Soch olish va turmak',
  'category_sub_makeup': 'Makiyaj va go‘zallik xizmatlari',
  'category_sub_massage': 'Massaj va SPA terapiyasi',
  'category_sub_nail_care': 'Manikyur va pedikyur',

  // Events & Photography
  'category_events_photo': 'Tadbirlar va fotografiya',
  'category_sub_event_photography': 'Tadbir va portret fotosurati',
  'category_sub_catering': 'Keytering va pazandachilik xizmatlari',
  'category_sub_event_planning': 'Tadbir va bayram tashkil qilish',
  'category_sub_dj_music': 'DJ va jonli musiqa ijrosi',

  // Automotive Services
  'category_automotive': 'Avtomobil xizmatlari',
  'category_sub_mobile_mechanic': 'Ko‘chma mexanik va diagnostika',
  'category_sub_car_wash': 'Ko‘chma avtomobil yuvish va parvarish',
  'category_sub_jump_start': 'Akkumulyatorni ishga tushirish va evakuatsiya',

  // Gardening & Outdoor
  'category_gardening': 'Bog‘dorchilik va tashqi hudud',
  'category_sub_lawn_mowing': 'Maysazor o‘rish va hovli parvarishi',
  'category_sub_landscaping': 'Landshaft dizayni va o‘simliklar bilan bezash',
  'category_sub_snow_removal': 'Qorni tozalash va muzni erittirish',
  'category_sub_pool_maintenance': 'Basseynni parvarish qilish va tozalash',

  // Lessons & Tutoring
  'category_lessons_tutoring': 'Darslar va repetitorlik',
  'category_sub_academic_tutoring': 'O‘quv fanlari va matematika bo‘yicha repetitorlik',
  'category_sub_language_lessons': 'Til darslari',
  'category_sub_music_lessons': 'Musiqa va cholg‘u asboblari darslari',
  'category_sub_fitness_training': 'Shaxsiy fitnes mashg‘ulotlari',

  // Business & Admin
  'category_business_admin': 'Biznes va maʼmuriy yordam',
  'category_sub_virtual_assistant': 'Virtual yordamchi xizmatlari',
  'category_sub_data_entry': 'Maʼlumot kiritish va terish',
  'category_sub_translation': 'Hujjatlarni tarjima qilish',
  'category_sub_graphic_design': 'Grafik dizayn va brending',
  // post job controller
  'post_job_time_placeholder': '--:--',
  'post_job_photo_limit_title': 'Chegaraga yetdingiz',
  'post_job_photo_limit_message': 'Faqat 3 tagacha rasm biriktirishingiz mumkin',
  'post_job_validation_missing_title_title': 'Nom kiritilmagan',
  'post_job_validation_missing_title_message': 'Iltimos, vazifa nomini kiriting',
  'post_job_validation_missing_category_title': 'Kategoriya tanlanmagan',
  'post_job_validation_missing_category_message': 'Iltimos, kategoriyani tanlang',
  'post_job_validation_missing_subcategory_title': 'Kichik kategoriya tanlanmagan',
  'post_job_validation_missing_subcategory_message': 'Iltimos, kichik kategoriyani tanlang',
  'post_job_validation_missing_location_title': 'Manzil kiritilmagan',
  'post_job_validation_missing_location_message': 'Iltimos, manzilni kiriting',
  'post_job_validation_missing_description_title': 'Tavsif kiritilmagan',
  'post_job_validation_missing_description_message': 'Iltimos, vazifani tavsiflang',
  'post_job_validation_missing_amount_title': 'Summa kiritilmagan',
  'post_job_validation_missing_amount_message': 'Iltimos, byudjet summasini kiriting',
  'post_job_validation_missing_rate_title': 'Narx kiritilmagan',
  'post_job_validation_missing_rate_message': 'Iltimos, soatlik narxni kiriting',
  'post_job_validation_missing_start_time_title': 'Boshlanish vaqti kiritilmagan',
  'post_job_validation_missing_start_time_message': 'Iltimos, boshlanish vaqtini tanlang',
  'post_job_validation_missing_end_time_title': 'Tugash vaqti kiritilmagan',
  'post_job_validation_missing_end_time_message': 'Iltimos, tugash vaqtini tanlang',
  'post_job_success_title': 'Muvaffaqiyat',
  'post_job_failed_title': 'Xato',
  'nav_home': 'Bosh sahifa',
  'nav_chat': 'Chat',
  'nav_my_jobs': 'Mening ishlarim',
  'nav_profile': 'Profil',
  'post_job_summary_header_review': 'Ko‘rib chiqish va ',
  'post_job_summary_header_confirm': 'tasdiqlash',
  'post_job_summary_header_subtitle': 'Joylashtirishdan oldin barchasini tekshiring',
  'post_job_summary_task_details_title': 'Vazifa tafsilotlari',
  'post_job_summary_title_label': 'Nomi',
  'post_job_summary_subcategory_label': 'Kichik kategoriya',
  'post_job_summary_location_label': 'Manzil',
  'post_job_summary_budget_payment_title': 'Byudjet va to‘lov',
  'post_job_summary_budget_type_label': 'Byudjet turi',
  'post_job_summary_date_label': 'Sana',
  'post_job_summary_budget_fixed_price': 'Belgilangan narx',
  'post_job_summary_budget_hourly_rate': 'Soatlik narx',
  'post_job_summary_budget_negotiable': 'Kelishiladigan',
  'post_job_summary_amount_one_time': '(bir martalik)',
  'post_job_summary_amount_per_hour': '/ soat',
  'post_job_summary_amount_hrs_suffix': 'soat',
  'post_job_summary_amount_negotiable_desc': 'Chatda muhokama qilinadi',
  'post_job_summary_edit_details_button': 'Tafsilotlarni tahrirlash',
  'post_job_summary_confirm_submit_button': 'Tasdiqlash va yuborish',
  'role_ctrl_err_title': 'Tanlash xatosi',
  'role_ctrl_err_msg': 'Davom etish uchun rolni tanlang.',
  'tab_all': 'Barchasi',
  'tab_pending': 'Ko‘rib chiqilmoqda',
  'tab_ongoing': 'Davom etayotgan',
  'tab_completed': 'Yakunlandi',
  'tab_cancelled': 'Bekor qilindi',
  'chat_list_title': 'Xabarlar',
  'chat_list_search_hint': 'Suhbatlarni qidirish...',
  'chat_list_no_conversations': 'Hozircha suhbatlar yo‘q',
  'chat_tile_no_message': 'Hozircha xabar yo‘q',
  'chat_controller_error_title': 'Xato',
  'chat_controller_session_expired': 'Kirish sessiyasi topilmadi, iltimos qayta tizimga kiring.',
  'message_screen_error_title': 'Xato',
  'message_screen_send_failed_title': 'Xabar yuborilmadi',
  'message_screen_empty_state': 'Hozircha xabarlar yo‘q. Suhbatni boshlash uchun birinchi xabarni yuboring.',
  'message_screen_voice_message': 'Ovozli xabar',
  'message_screen_input_hint': 'Xabar yozing...',
  'notification_time_just_now': 'HOZIRGINA',
  "notification_screen_mark_all_read":"Hammasini o‘qish",
  'notification_time_min_ago': 'DAQIQA OLDIN',
  'notification_time_hour_ago': 'SOAT OLDIN',
  'notification_time_day_ago': 'KUN OLDIN',
  'notification_time_month_ago': 'OY OLDIN',
  'notification_time_year_ago': 'YIL OLDIN',
  'notification_screen_title': 'Bildirishnomalar',
  'notification_screen_tab_inbox': 'Kiruvchi',
  'notification_screen_tab_settings': 'Sozlamalar',
  'notification_screen_load_error_fallback': 'Bildirishnomalarni yuklab bo‘lmadi',
  'notification_screen_error_title': "Bildirishnomalarni yuklab bo‘lmadi",
  'notification_screen_empty_title': 'Hozircha bildirishnomalar yo‘q',
  'notification_screen_empty_subtitle': "Yangi narsa paydo bo‘lganda sizga xabar beramiz.",
  'notification_screen_retry_button': 'Qayta urinish',
  'notification_screen_push_title': 'Push-bildirishnomalar',
  'notification_screen_push_subtitle': 'Tezkor ogohlantirishlar',
  'notification_screen_email_title': 'Elektron pochta bildirishnomalari',
  'notification_screen_email_subtitle': 'Elektron pochta xabarlari',
  'notification_screen_sms_title': 'SMS bildirishnomalari',
  'notification_screen_sms_subtitle': 'SMS yangilanishlari',
  'notification_screen_sound_title': 'Ovozli bildirishnomalar',
  'notification_screen_sound_subtitle': 'Ilova ovoz effektlari',
  'worker_active_jobs_title': 'Faol ishlar',
  'worker_active_jobs_empty': 'Hozircha faol ishlar yo‘q.',
  'worker_job_negotiable': 'Kelishiladigan',
  'worker_job_not_specified': 'Ko‘rsatilmagan',
  'worker_job_payment_cash': 'Naqd',
  'worker_job_payment_card': 'Karta',
  'worker_job_payment_escrow': 'Eskrou',
  'worker_job_payment_commission': 'Faqat komissiya',
  'worker_job_client_fallback': 'Mijoz',
  'worker_home_no_jobs_in_category': 'Hozircha @category kategoriyasida ishlar mavjud emas.',
  'worker_home_city_required_title': 'Shahar talab qilinadi',
  'worker_home_city_required_message': 'Mavjud ishlarni ko‘rish uchun shahringizni kiriting.',
  'worker_home_add_city_title': 'Shahringizni qo‘shing',
  'worker_home_add_city_subtitle': 'Yaqin atrofda joylashtirilgan ishlarni ko‘rsatishimiz uchun shahringizni ayting.',
  'worker_home_city_hint': 'masalan, Multan, Lahor, Karachi',
  'worker_home_find_jobs_button': 'Ishlarni topish',
  'worker_home_jobs_in_city': '@city shahridagi ishlar',
  'worker_home_swipe_subtitle': 'Eng yaxshi imkoniyatlarni ko‘rish uchun suring',
  'worker_home_no_jobs_in_city': 'Hozircha @city shahrida ishlar mavjud emas.',
  'worker_home_welcome': 'Xush kelibsiz',
  'worker_home_online': 'ONLAYN',
  'worker_home_offline': 'OFLAYN',
  'worker_home_earnings_label': 'DAROMAD',
  'worker_home_active_label': 'FAOL',
  'worker_job_card_selected': 'Ishchi tanlandi',
  'worker_job_card_see_detail': 'Batafsil',
  'worker_job_history_tab_all': 'Barchasi',
  'worker_job_history_tab_active': 'Faol',
  'worker_job_history_tab_past': 'O‘tgan','worker_job_detail_submitting_application': 'Ariza yuborilmoqda...',
  'worker_job_detail_success_title': 'Muvaffaqiyat',
  'worker_job_detail_application_update_title': 'Ariza yangilandi',
  'worker_job_detail_not_found': 'Ish topilmadi',
  'worker_job_detail_cancelling_job': 'Ish bekor qilinmoqda...',
  'worker_job_detail_job_cancelled_title': 'Ish bekor qilindi',
  'worker_job_detail_action_failed_title': 'Amal bajarilmadi',
  'worker_job_detail_marking_completed': 'Ish bajarilgan deb belgilanmoqda...',
  'worker_job_detail_job_completed_title': 'Ish bajarildi',
  'worker_job_detail_overview_title': 'Umumiy ma’lumot',
  'worker_job_detail_label_category': 'Kategoriya',
  'worker_job_detail_label_city': 'Shahar',
  'worker_job_detail_label_location': 'Manzil',
  'worker_job_detail_label_status': 'Holat',
  'worker_job_detail_budget_title': 'Byudjet va to‘lov',
  'worker_job_detail_label_amount': 'Summa',
  'worker_job_detail_label_payment_mode': 'To‘lov usuli',
  'worker_job_detail_schedule_title': 'Jadval',
  'worker_job_detail_label_date_time': 'Sana va vaqt',
  'worker_job_detail_description_title': 'Tavsif',
  'worker_job_detail_no_description': 'Tavsif kiritilmagan.',
  'worker_job_detail_posted_by_title': 'Joylashtirgan',
  'worker_job_detail_completed_banner': 'Siz bu ishni bajarilgan deb belgiladingiz.',
  'worker_job_detail_cancelled_banner': 'Bu ish bekor qilindi.',
  'worker_job_detail_chat_with_client': 'Mijoz bilan suhbat',
  'worker_job_detail_cancel_job_button': 'Ishni bekor qilish',
  'worker_job_detail_mark_completed_button': 'Bajarildi deb belgilash',
  'worker_job_detail_taken_by_other_banner': 'Bu ish allaqachon boshqa ishchiga tayinlangan.',
  'worker_job_detail_waiting_confirmation': "Siz ariza berdingiz. Mijozning tasdiqlashini kuting.",
  'worker_job_detail_apply_button': 'Ariza berish',
  'worker_job_detail_online_pill': 'Onlayn',
  'worker_job_detail_offline_pill': 'Oflayn',
  'worker_job_detail_photos_title': 'Rasmlar',
  'worker_job_detail_photo_count_singular': '@count ta rasm',
  'worker_job_detail_photo_count_plural': '@count ta rasm',
  'job_history_card_payout_label': 'TO‘LOV:',
  'worker_history_no_title': 'Nomsiz',
  'worker_history_location_not_specified': 'Manzil ko‘rsatilmagan',
  'worker_history_na': 'Mavjud emas',
  'worker_history_status_posted': 'JOYLASHTIRILGAN',
  'worker_history_status_applied': 'ARIZA BERILGAN',
  'worker_my_jobs_title': 'Mening ishlarim',
  'worker_my_jobs_empty': 'Ishlar topilmadi',
  'worker_edit_profile_title': 'Profilni tahrirlash',
  'worker_edit_profile_take_photo': 'Rasmga olish',
  'worker_edit_profile_choose_gallery': 'Galereyadan tanlash',
  'worker_edit_profile_no_email': 'Elektron pochta bilan ro‘yxatdan o‘tilmagan',
  'worker_edit_profile_change_photo': 'Rasmni o‘zgartirish',
  'worker_edit_profile_hint_full_name': 'To‘liq ism',
  'worker_edit_profile_hint_email': 'Elektron pochta manzili',
  'worker_edit_profile_hint_phone': 'Telefon raqami',
  'worker_edit_profile_skills_label': 'KO‘NIKMALAR',
  'worker_edit_profile_hint_add_skill': 'Ko‘nikma qo‘shish',
  'worker_edit_profile_cancel_button': 'Bekor qilish',
  'worker_edit_profile_saving_button': 'Saqlanmoqda...',
  'worker_edit_profile_save_button': 'O‘zgarishlarni saqlash',
  'worker_favourites_title': 'Sevimlilar',
  'worker_favourites_empty_title': 'Hozircha sevimli ishlar yo‘q.',
  'worker_favourites_empty_subtitle': 'Ishni bu yerda saqlash uchun yurak belgisini bosing.',
  'worker_help_tab_faqs': 'Savol-javoblar',
  'worker_help_tab_submit_ticket': 'Murojaat yuborish',
  'worker_help_tab_live_chat': 'Jonli chat',
  'worker_help_appbar_title': 'Yordam va qo‘llab-quvvatlash',
  'worker_help_live_badge': '24/7 FAOL',
  'worker_help_kb_section_title': 'BILIMLAR BAZASI VA SAVOL-JAVOBLAR',
  'worker_help_no_results': 'Natijalar topilmadi',
  'worker_help_direct_assistance_title': 'TO‘G‘RIDAN-TO‘G‘RI YORDAM',
  'worker_help_call_support_label': 'QO‘LLAB-QUVVATLASHGA QO‘NG‘IROQ',
  'worker_help_email_us_label': 'BIZGA YOZING',
  'worker_help_search_hint': 'Javoblar, qo‘llanmalarni qidirish...',
  'worker_help_label_category': 'Kategoriya',
  'worker_help_label_subject': 'Mavzu',
  'worker_help_label_detailed_message': 'Batafsil xabar',
  'worker_help_select_category_hint': 'Kategoriyani tanlang',
  'worker_help_subject_hint': 'Muammoning qisqacha tavsifi...',
  'worker_help_message_hint': 'So‘rovingizga oid barcha tegishli tafsilotlarni kiriting...',
  'worker_help_submit_ticket_button': 'Murojaat yuborish',
  'worker_help_support_ai_name': 'Uybor AI yordamchisi',
  'worker_help_online_operator': 'ONLAYN OPERATOR',
  'worker_help_chat_input_hint': 'Savolingizni yozing...',
  'faq_escrow_question': 'To‘lovlarni eskrou orqali saqlash tizimi qanday ishlaydi?',
  'faq_escrow_answer': 'Ishchi yollaganingizda, to‘lovingiz xavfsiz tarzda eskrouda saqlanadi va faqat ish bajarilgan deb belgilanib, siz tomondan tasdiqlanganidan so‘ng unga o‘tkaziladi.',
  'faq_category_payment': 'To‘lov',
  'faq_fees_question': 'Ro‘yxatdan o‘tish uchun xizmat haqi bormi?',
  'faq_fees_answer': 'Hisob yaratish va platformadan foydalanish butunlay bepul. Kichik xizmat haqi faqat ish muvaffaqiyatli yakunlanganda olinadi.',
  'faq_verification_question': 'Ishchilarni tasdiqlash nishonlari qanday ishlaydi?',
  'faq_verification_answer': 'Ishchilar amaldagi shaxsni tasdiqlovchi hujjatlarni taqdim etib, tekshiruv jarayonidan o‘tgach tasdiqlash nishonlarini oladi, bu esa sizga ishonch bilan ishga olishga yordam beradi.',
  'faq_category_verification': 'Tasdiqlash',
  'faq_dispute_question': 'Nizo yuzaga kelsa, nima qilishim kerak?',
  'faq_dispute_answer': '«Murojaat yuborish» bo‘limidan kelishmovchilik tafsilotlari bilan murojaat oching. Jamoamiz vaziyatni ko‘rib chiqib, adolatli yechim topishga yordam beradi.',
  'faq_category_disputes': 'Nizolar',
  'faq_safety_question': 'Shaxsiy ma’lumotlarim qanday himoyalanadi?',
  'faq_safety_answer': 'Barcha shaxsiy ma’lumotlar uzatishda va saqlashda shifrlanadi hamda sizning aniq roziligingizsiz uchinchi tomonlarga hech qachon berilmaydi.',
  'faq_category_safety': 'Xavfsizlik',
  'faq_cancel_question': 'Xavfsiz depozit qilinganidan keyin ishni bekor qila olamanmi?',
  'faq_cancel_answer': 'Ha, ishchi ishni boshlashidan oldin bekor qilishingiz mumkin. Vaqtga qarab, qoidalarimizga muvofiq qisman bekor qilish haqi olinishi mumkin.',
  'faq_cat_all': 'Barcha maqolalar',
  'faq_cat_payment': 'To‘lov',
  'faq_cat_verification': 'Tasdiqlash',
  'faq_cat_disputes': 'Nizolar',
  'faq_cat_safety': 'Xavfsizlik',
  'ticket_cat_payment': 'To‘lov va eskrou',
  'ticket_cat_verification': 'Tasdiqlash',
  'ticket_cat_disputes': 'Nizolar',
  'ticket_cat_account': 'Hisob',
  'ticket_cat_tech': 'Texnik muammo',
  'ticket_cat_other': 'Boshqa',
  'chat_welcome_msg': 'Salom! Qo‘llab-quvvatlash xizmatiga xush kelibsiz. Sizga qanday yordam bera olamiz?',
  'chat_time_just_now': 'Hozirgina',
  'chat_time_now': 'Hozir',
  'chat_auto_reply': 'Murojaat qilganingiz uchun rahmat, mutaxassislarimizdan biri tez orada javob beradi.',
  'ticket_missing_title': 'Maʼlumotlar yetishmayapti',
  'ticket_missing_msg': 'Iltimos, mavzu va xabarni to‘ldiring.',
  'ticket_submitted_title': 'Murojaat yuborildi',
  'ticket_submitted_msg': 'Qo‘llab-quvvatlash jamoamiz tez orada siz bilan bog‘lanadi.',
  'worker_profile_oops_title': 'Voy!',
  'worker_profile_name_empty_error': 'Ism bo‘sh bo‘lishi mumkin emas.',
  'worker_profile_saving_loader': 'Saqlanmoqda...',
  'worker_profile_update_failed_title': 'Yangilash muvaffaqiyatsiz',
  'worker_profile_success_title': 'Muvaffaqiyat',
  'worker_profile_updated_success_message': 'Profil muvaffaqiyatli yangilandi!',
  'worker_profile_generic_error': 'Nimadir noto‘g‘ri ketdi, iltimos qayta urinib ko‘ring.',
  'worker_profile_add_name_placeholder': 'Ismingizni kiriting',
  'worker_profile_not_provided': 'Kiritilmagan',
  'worker_profile_im_a_role': "Men @role man",
  'worker_lang_title': 'Tilni tanlang',
  'worker_lang_eng_sub': 'INGLIZCHA',
  'worker_lang_uzb_sub': 'O‘ZBEKCHA',
  'worker_lang_rus_sub': 'RUSCHA',
  'wallet_success_title': 'Muvaffaqiyat',
  'wallet_deposit_success_message': '@amount miqdoridagi depozit muvaffaqiyatli amalga oshirildi',
  'wallet_insufficient_balance_title': 'Balans yetarli emas',
  'wallet_insufficient_balance_message': "Yechish uchun mablag‘ingiz yetarli emas",
  'wallet_withdraw_success_message': 'Mablag‘ muvaffaqiyatli yechildi',
  'worker_profile_title': 'Profil',
  'worker_profile_online': 'ONLAYN',
  'worker_profile_offline': 'OFLAYN',
  'worker_profile_personal_info': 'Shaxsiy maʼlumot',
  'worker_profile_wallet': 'Hamyon',
  'worker_profile_favourites': 'Sevimlilar',
  'worker_profile_location': 'Manzil',
  'worker_profile_location_sub': 'Yaqin atrofdagi ishlar uchun faol',
  'worker_profile_settings': 'Sozlamalar',
  'worker_profile_help_support': 'Yordam va qo‘llab-quvvatlash',
  'worker_profile_logout': 'Chiqish',
  'worker_profile_logout_title': 'Chiqish',
  'worker_profile_logout_subtitle': 'Tizimdan chiqishni xohlaysizmi?',
  'deposit_popup_title': 'Mablag‘ kiritish',
  'deposit_popup_select_card_type': 'KARTA TURINI TANLANG',
  'deposit_popup_label_amount': 'SUMMA (\$)',
  'deposit_popup_hint_amount': '\$ 50.00',
  'deposit_popup_label_card_number': 'KARTA RAQAMI',
  'deposit_popup_hint_card_number': '8600 **** **** ****',
  'deposit_popup_top_text_card_number': 'UZCARD (8600)',
  'deposit_popup_label_expiry': 'AMAL QILISH MUDDATI',
  'deposit_popup_hint_expiry': 'OO/YY',
  'deposit_popup_label_cvv': 'CVV',
  'deposit_popup_hint_cvv': '***',
  'deposit_popup_label_cardholder_name': 'KARTA EGASINING ISMI',
  'deposit_popup_hint_cardholder_name': 'AZIZ AZIZOV',
  'deposit_popup_confirm_button': 'Depozitni tasdiqlash',
  'worker_settings_title': 'Sozlamalar',
  'worker_settings_language': 'Tilni tanlang',
  'worker_settings_notifications': 'Bildirishnomalar',
  'worker_settings_dark_mode': 'Tungi rejim',
  'worker_settings_dark_mode_sub': 'Yorug‘ va qorong‘i rejim o‘rtasida almashtirish',
  'worker_settings_become_client': 'Mijoz bo‘lish',
  'worker_settings_switch': 'Almashtirish',
  'worker_settings_app_version': 'Ilova versiyasi',
  'worker_settings_version_val': '1.2.0 (Barqaror)',
  'worker_settings_acc_status': 'Hisob holati',
  'worker_settings_verified': 'Tasdiqlangan',
  'worker_settings_security': 'Xavfsizlik',
  'worker_settings_security_val': 'SSL/SMS bilan himoyalangan',
  'withdraw_popup_title': 'Mablag‘ yechish',
  'withdraw_popup_method_card': 'Karta',
  'withdraw_popup_method_bank_account': 'Bank hisobi',
  'withdraw_popup_label_amount': 'SUMMA (\$)',
  'withdraw_popup_available_balance': 'MAVJUD: @amount',
  'withdraw_popup_hint_amount': '\$ 100.00',
  'withdraw_popup_label_iban': 'BANK HISOBI (IBAN)',
  'withdraw_popup_hint_iban': 'UZ99 4321 0000 1234 5678',
  'withdraw_popup_confirm_button': 'Yechishni tasdiqlash',
  'worker_wallet_title': 'Hamyon',
  'worker_wallet_recent_transactions': 'So‘nggi tranzaksiyalar',
  'worker_wallet_see_all': 'Barchasini ko‘rish',
  'worker_wallet_total_balance': 'Umumiy balans',
  'worker_wallet_deposit_button': '+ Depozit',
  'worker_wallet_withdraw_button': '- Yechish',
  'worker_wallet_tx_plumbing_title': 'Santexnika uchun to‘lov',
  'worker_wallet_tx_bank_withdrawal_title': 'Bankka o‘tkazma',
  'worker_wallet_tx_hvac_title': 'Isitish/shamollatish uchun to‘lov',
  'worker_wallet_tx_time_today': 'Bugun, 14:30',
  'worker_wallet_tx_time_yesterday': 'Kecha, 16:15',
  'worker_wallet_tx_time_mar5': '5-mart, 11:20',
  'worker_personal_info_title': 'Shaxsiy maʼlumot',
  'worker_personal_info_full_name_label': 'TO‘LIQ ISM',
  'worker_personal_info_email_label': 'ELEKTRON POCHTA MANZILI',
  'worker_personal_info_phone_label': 'TELEFON RAQAMI',
  'worker_personal_info_skills_label': 'KO‘NIKMALAR',
  'worker_personal_info_no_skills': 'Hozircha ko‘nikmalar qo‘shilmagan',
  'worker_personal_info_edit_button': 'Profilni tahrirlash',
  'worker_bottom_nav_home': 'Bosh sahifa',
  'worker_bottom_nav_chat': 'Chat',
  'worker_bottom_nav_my_jobs': 'Mening ishlarim',
  'worker_bottom_nav_profile': 'Profil',
  'client_bottom_nav_home': 'Bosh sahifa',
  'client_bottom_nav_chat': 'Chat',
  'client_bottom_nav_my_jobs': 'Mening ishlarim',
  'client_bottom_nav_profile': 'Profil',
  'role_selection_title_line1': 'Siz kimsiz',
  'role_selection_title_line2': '?',
  'role_selection_post_job': 'Ish joylash',
  'role_selection_find_work': 'Ish topish',
  'role_selection_continue': 'Davom etish',
  'role_selection_error_title': 'Xato',
  'role_selection_error_message': 'Davom etish uchun rolni tanlang',
  'languagesheettitle':'Tilingizni tanlang',
  'languagesheetsubtitle':'Buni istalgan vaqtda Sozlamalar orqali o‘zgartirishingiz mumkin.',
  'languagesheetloading':'Iltimos kuting...',
  'languagesheetcontinue':'Davom etish',
  "edit_profile_section_personal": "Shaxsiy ma'lumotlar",
  "edit_profile_email_locked_note": "Elektron pochtani o'zgartirib bo'lmaydi",
  "edit_profile_btn_saving": "Saqlanmoqda...",
  "worker_edit_profile_section_personal": "Shaxsiy ma'lumotlar",
  "worker_edit_profile_email_locked_note": "Elektron pochtani o'zgartirib bo'lmaydi",
  "worker_edit_profile_no_skills_yet": "Hali ko'nikmalar qo'shilmagan",
  "worker_personal_info_section_contact": "Aloqa ma'lumotlari",
  "personal_info_section_contact": "Aloqa ma'lumotlari",
  "workersettingsnack":"...ga o‘tdi",
  "post_job_image_pick_error_title": "Xato",
  "post_job_image_pick_error_message": "Rasmni tanlashda xatolik yuz berdi. Iltimos, qayta urinib ko‘ring.",
  'wallet_error_title': 'Xato',
  'wallet_error_not_logged_in': 'Iltimos, avval tizimga kiring.',
  'wallet_error_invalid_amount': 'Iltimos, yaroqli miqdorni kiriting.',
  'wallet_error_something_went_wrong': 'Nimadir noto‘g‘ri ketdi. Iltimos, qayta urinib ko‘ring.',
  'wallet_topup_success': 'Hisob muvaffaqiyatli to‘ldirildi',
  'wallet_topup_failed': 'Hisobni to‘ldirish muvaffaqiyatsiz yakunlandi',
  'deposit_popup_processing': 'Ishlov berilmoqda...',
  'post_job_estimating_fee': 'Platforma to‘lovi hisoblanmoqda...',
  'post_job_platform_fee_label': 'Platforma uchun to‘lov',
  'post_job_total_to_pay_label': 'To‘lanadigan umumiy summa',
};